### ISSUE TITLE
IRR AS-SET

### ISSUE THREAD

**Issue by respawner** [respawner/peering-manager#1]
_Summary: Handling IRR AS-SET is a pain._

Autonomous systems can specify multiple AS-SET to be used (per IRR, per IP version, etc…).
For now we are using 2 fields for AS-SET (for IPv6 and IPv4). We should probably stop doing this and provide only one field where data should be formatted properly.

The PeeringDB project is facing the same issue (peeringdb/peeringdb#151), and since we want our data to come from their, maybe we should wait (and assist if we can) for them to deal with it.

**Comment by jnikoletich** [comment]
Any movement on this? Would love to sponsor some time on this.
