### ISSUE TITLE
Routing Policies numerical/alphabetical order

### ISSUE THREAD

**Issue by FredNeuberger** [respawner/peering-manager#100]
### Environment
* Python version:  3.5.3-1
* Peering Manager version:  master

No matter what I do, Routing Policies seem to be added in numerical and then alphabetical order.

Not sure about other vendors, but with Juniper, the order is might be important, especially when you configure them like the standard Juniper PM template does.
There are other ways to chain them in JunOS, but that would be a different story and probably a FR.

Thank you for all the amazing work that you have put into this piece of software :)

**Comment by respawner** [comment]
That's true. With Juniper policies chaining order is important and can lead to unexpected issues if not done properly. Adding a `weight` field could help sorting policies and using them in the right order.
