### ISSUE TITLE
Ability to fetch generated config via API

### ISSUE THREAD

**Issue by adamgent** [respawner/peering-manager#101]
### Environment
* Python version:  3.6.6
* Peering Manager version:  master

### Proposed Functionality
Ability to fetch the generated configuration for an IX via the API

Ideally it can be fetched in a "raw" format as well as JSON - this retains the formatting for easy merging of the configuration into other tools.

### Use Case
We are using an automated deployment workflow that ships a "Full Config" to the device each time, which would overwrite changes made via NAPALM directly by peering-manager.
If we can request the configuration via API we can include this in our existing deployment workflow.

**Comment by respawner** [comment]
Already implemented as discussed on slack.
