### ISSUE TITLE
Django Issues After Migrating from SQLite to PostgreSQL

### ISSUE THREAD

**Issue by phyrun404** [respawner/peering-manager#105]
Hi,

I believe I did everything right when following the directions at https://peering-manager.readthedocs.io/en/latest/setup/postgresql/ but now the site appears to be broken.  In particular, I am getting these errors while navigating the site:

```
<class 'django.urls.exceptions.NoReverseMatch'>
'peering-api' is not a registered namespace

<class 'django.urls.exceptions.NoReverseMatch'>
Reverse for 'direct_peering_session_list' not found. 'direct_peering_session_list' is not a valid view function or pattern name.

<class 'django.template.exceptions.TemplateDoesNotExist'>
auth/login.html
```

This is the contents of the urls.py file.  Please let me know if there are any other files that I can post that would be helpful:

```
from django.conf import settings
from django.conf.urls import include, url

from . import views
from .admin import admin_site
from users.views import LoginView, LogoutView


handler500 = views.handle_500

__patterns = [
    # Include the peering app
    url(r"", include("peering.urls")),
    # Include the peeringdb app
    url(r"", include("peeringdb.urls")),
    # Include the users app
    url(r"^user/", include("users.urls")),
    # Include the utils app
    url(r"", include("utils.urls")),
    # Users login/logout
    url(r"^login/$", LoginView.as_view(), name="login"),
    url(r"^logout/$", LogoutView.as_view(), name="logout"),
    # Home
    url(r"^$", views.Home.as_view(), name="home"),
    # Admin
    url(r"^admin/", admin_site.urls),
    # Error triggering
    url(r"^error500/$", views.trigger_500),
    # API
    url(r"^api/$", views.APIRootView.as_view(), name="api-root"),
    url(r"^api/peering/", include("peering.api.urls")),
    url(r"^api/peeringdb/", include("peeringdb.api.urls")),
]

# Prepend BASE_PATH
urlpatterns = [url(r"^{}".format(settings.BASE_PATH), include(__patterns))]
```

----

Any ideas as to what I may have broke and how to go about fixing it?  Thanks!

**Comment by respawner** [comment]
These error seems to be related to an inconsistent code base. Basically it tries to use code that is not there and your end up seeing those issues. Did you follow [this specific part](https://peering-manager.readthedocs.io/en/latest/setup/postgresql/#migrating-from-sqlite) of the documentation?

**Comment by phyrun404** [comment]
Hi,

Thanks for the response.  I did follow those directions, but I'm pretty sure I goofed up somewhere along the way.  We were able to get the site back to a workable state.  

Thanks again or all your good work.  Jeff from Xfernet just sent some good vibes your way.

**Comment by respawner** [comment]
Good. The SQLite to PostgreSQL migration is still some kind of witchcraft so if you managed to get it working it means you are pretty good at magic. More seriously if you see anything wrong due to that migration feel free to open an issue so I can investigate the problem.
