### ISSUE TITLE
IOS XR specific session password format

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#113]
### Environment
* Python version: 3.5.3
* Peering Manager version:  master

### Steps to Reproduce

Apply a password to a peering session on an IX mapped to a Cisco XR device

### Expected Behavior

Password applied as `password encrypted 045612150A22595C0C090404011C03162E`

### Observed Behavior

Password applied as `password encrypted 7 045612150A22595C0C090404011C03162E`

**Comment by respawner** [comment]
You could use something like this in a template:

```
{# Check if the password is encrypted #}
{% if session.password.startswith("7 ") %}
password encrypted {{ session.password[2:] }}
{% else %}
password {{ session.password }}
{% endif %}
```

A helper filter exposed to the Jinja2 templating engine could help though.
