### ISSUE TITLE
eBGP multi-hop session

### ISSUE THREAD

**Issue by gdelafond** [respawner/peering-manager#114]
### Environment
* Peering Manager version:  master (e92acfde892126eacd106a369b87f01ae82795f7)

### Proposed Functionality

Add a way to configure eBGP multi-hop session.

On Cisco IOS, we will need to set the following information on the neighbor:
```
- ebgp-multihop [count]:         Allow EBGP neighbors not on directly connected networks 
- update-source interface-name:  Source of routing updates
```

`count` is a number between 1 and 255 (with a default to 255?).
`update-source` is an interface name so I think it should be a text field.

### Use Case

Configure eBGP multi-hop sessions ;-)

### External Dependencies

None

**Comment by gdelafond** [comment]
PS: `update-source interface-name` can be used whithout setting ebgp-multihop (in some case it is usefull to set it for classical eBGP session).

**Comment by respawner** [comment]
I would tend to use `1` as default for the multihop option, which is the default for eBGP sessions if the value is not changed to another.

**Comment by gdelafond** [comment]
I said 255 because Cisco default value is 255 when just setting `ebgp-multihop`.
