### ISSUE TITLE
Ability to send templated peering request emails

### ISSUE THREAD

**Issue by adamgent** [respawner/peering-manager#119]
### Environment
* Python version:  3.6.3
* Peering Manager version:  master

### Proposed Functionality
Ability to email prospective/current peers requesting peering using template(s).
- be able to automatically send list of mutual IX connections to prospective peers
- option to email peers with "missing" sessions
- allow for emailing large numbers of peers, but carefully to avoid spamming! (maybe a configurable threshold for max emails?)
- can choose peers from "available peers" view on any IX and still automatically send mutual IX list
- keep track of peers that were already emailed in last "x" days to avoid duplicates

### Use Case
Requesting new peerings at large IXes can be very time-consuming, particularly where route-servers are less popular but many networks peer openly via bilateral sessions.

Also great for maintaining existing peering relationships where new mutual IXs are added by peers and sessions are missing.

This should allow a better way to request these peering sessions using the data we already have in peering-manager.

**Comment by FredNeuberger** [comment]
Uh, very nice feature request. I would love to have that too :)

**Comment by XioNoX** [comment]
Indeed it would be very useful!
Some thoughts around it:
- A "click here" link in the email so peering-manager automatically adds the session (or notify us, or add the session to a "to be reviewed" list, etc)
- Keep track of the networks that have refused to peer (at all or at some IXPs)
- Is aware of existing sessions "We already peer in IXP X, but not in Y, would you like to peer there too?"
- Leverage some PeeringDB fields, for example "don't send peering request if already peer with RS" or "Don't send peering requests to networks that have outbound traffic ratios
- It can also be tricky to figure out what the proper peering contact is from the "Contact Information" list.
