### ISSUE TITLE
Multiple ASN's

### ISSUE THREAD

**Issue by jontyhewlett** [respawner/peering-manager#121]
Hi, 
Just to understand the software better - we operate multiple ASN's.  The config file accepts just one.  Should we therefore have a copy of Peering manager per ASN (we usually have 2 connections into each IX, one for each ASN).
Thanks
J.

**Comment by respawner** [comment]
For now Peering Manager can operate only one ASN. So if you want to use it for all your ASNs you'll need one copy of Peering Manager per ASN (I agree that it is not great).

It is possible that at some point we can rewrite some of the code to make it capable of handling several ASNs. I'm not sure that I'll be able to make this happen for the first stable release though.

**Comment by jontyhewlett** [comment]
Thanks very much for the clarification.  I just wanted to be sure I wasn't missing a feature.  Thanks for your hard work
