### ISSUE TITLE
Implement More IX Peer Types

### ISSUE THREAD

**Issue by ggiesen** [respawner/peering-manager#123]
### Environment
* Python version:  3.6.6
* Peering Manager version:  0.99-dev

### Proposed Functionality
Implement more IX peer types so that different configurations can be generated based on the various peer types:

- Direct Peer
- Peer Through Route Server (no direct session)
- Route Server
- Route Collector

There would be 3 radio buttons (mutually exclusive):

    Normal (selected by default)
    Route Server
    Route Collector

If "Normal" is selected, then a second set of radio buttons would be enabled with the following choices:

    Direct
    Through Route Server
    Both

This should cover off the majority of peer types, and being able to filter on these would allow generation of different configs for different peer types:

    Normal Direct - Create neighbor and associated policies
    Normal Through Route Server - Don't create a BGP neighbor, just create associated policies (and apply them to route server peers)
    Normal Both - Create neighbor and associated policies, and apply associated policies to route server peers
    Route Server - Create neighbor and associated policies (that differ from Normal and Route Collector peer types)
    Route Collector - Create neighbor and associated policies (that differ from Normal and Route Server peer types - typically deny all inbound prefixes)

### Use Case
Currently Peering Manager has no ability to generate configurations specific to peers that are only available through route servers (no direct session), or for route collectors. The only choice for the former is to generate generic route server configurations, which don't allow us to take advantage of many modern features that route servers support (BGP communities for AS prepending, no-export, etc), making route server-only peers second-class peers. Enabling a peer type for them would allow the generation of policies and config specific to those peer types, closing the functionality gap between direct peers and route server-only peers.

As for route collector peers, currently the only solution available is to ignore configuration for them completely, and to hard-code the configuration in the template.

Being able to select from a variety of peer types, and reference them in templates, removes these obstacles.

**Comment by ggiesen** [comment]
The more I've been thinking about this, the more I think this is how it should be done:

Similar to the "Route Server " checkbox, I would create 3 other categories of peers (that we can filter on in templates):

- Direct Peer (checked by default)
- Route Monitor
- Peer Through Route Server

A peer could follow under more than one of these categories (for example, you receive their prefixes both through a route server and directly), so I would use non-exclusive checkboxes rather than radio buttons.

**Comment by respawner** [comment]
Maybe this could benefit from the tagging system mentioned in #150.

**Comment by respawner** [comment]
As #150 has been implemented, could you test if the tagging system can fit the mentioned use cases?

I was thinking that it could be use to tag the peering sessions with tags representing the different types. Then checking the tags inside the template (using the `tags` field attached to each session) to decide what to do with the sessions depending on how they are tagged.

**Comment by ggiesen** [comment]
Yes, the new tagging system seem to work. It would be ideal though if we could predefine tags and select them from a drop-down (in addition to specifying them free-form)

**Comment by respawner** [comment]
The tagging system is at its beginning of the implementation so they are room to improve it. Glad to know that tags can help solving this issue though.

**Comment by respawner** [comment]
Closing as the tagging system solves this issue. Also tags are going to be improved by #175.
