### ISSUE TITLE
Use NetBox API to pull data from routers

### ISSUE THREAD

**Issue by 2bithacker** [respawner/peering-manager#124]
### Environment
* Python version:  3.6.7
* Peering Manager version:  master

### Proposed Functionality

NetBox has a REST API endpoint to execute arbitrary NAPALM methods against devices. Peering Manager could make use of this to access information from the routers without needing it's own NAPALM configuration and direct access to the devices.

This interface is read-only however, so it cannot be used for deploying templates.

```
> curl -s  'https://netbox.local/api/dcim/devices/171/napalm/?method=get_facts' | jq .
{
  "get_facts": {
    "fqdn": "router.example",
    "serial_number": "123456789",
    "os_version": "17.3R2-S2.1",
    "uptime": 5525652,
    "interface_list": [/REMOVED/],
    "vendor": "Juniper",
    "hostname": "router",
    "model": "MX960"
  }
}
```

### Use Case

If Peering Manager is being used for tracking peering information but the ability to push templates is not required, using NetBox's API removed the need for Peering Manager to have login information for the routers or direct access to them.

### External Dependencies

Not required, but pulling in [pynetbox](https://github.com/digitalocean/pynetbox) would simplify communications with the NetBox API.

### Notes

Brought this up in the NetworkToCode Slack already and have a PR ready to go, just wanted to submit the issue for tracking purposes and to explain some of the reasoning behind the PR.

**Comment by 6303210121** [comment]
Hi,
I recently created netbox but don't know how to add devices and how to fetch my router details .Can anyone guide me ?

Thanks & regards
Avinash

**Comment by netravnen** [comment]
> Hi, I recently created netbox but don't know how to add devices and how to fetch my router details .Can anyone guide me ?

Did you read the docs?

https://peering-manager.readthedocs.io/en/latest/models/peering/router/#in-peering-manager

https://www.youtube.com/playlist?list=PL7sEPiUbBLo_iTds-NV-9Tu05Gg2Aj8N7

https://www.youtube.com/playlist?list=PL7sEPiUbBLo8xMFZWBG8HFRDpXHfcZQ46

https://www.youtube.com/playlist?list=PLGi2LPn3CWpoldqkjrydrYPbTJ_Ba3uMC
