### ISSUE TITLE
Issues when discovering existing sessions + NAPALM logging

### ISSUE THREAD

**Issue by FredNeuberger** [respawner/peering-manager#13]
Hey,

The discovery/import of existing sessions seems to be working to some extend, but I do see some problems:

- Incorrect display of imported session numbers at the top:
`Imported 5 autonomous systems`
`Imported 5 peering sessions`
`Showing 1-18 of 18`
So I'm seeing 18 rows of imported sessions.

- Sessions not being recognised:
Same example as above,  when checking our actual configuration, I do see 278 peers configured on that router, for that IXP

- Sometimes a second "Import from Router" will show that something has been imported (at the top highlighted in green), but there aren't any new sessions actually being added

Cheers

**Comment by FredNeuberger** [comment]
One more:
- Imported sessions but not being counted
'Imported 0 peering sessions '

In fact, I just configured 4 sessions with one ASN on that IXP, which we had sessions at other IXP already

**Comment by respawner** [comment]
There is indeed a bug in the code (counting imported sessions). It should be patched and live soon.

Also there is a bug in NAPALM that has been reported by me. So some IPv6 sessions might be ignored when trying to import them.

**Comment by FredNeuberger** [comment]
Okay, understood.

The thing is, it is not only that v6 sessions are being ignored, but also v4. Out of the 260 missing sessions, around 150 are v4.

Is there a way to get some debug output by manually executing the stuff that PM does with NAPALM in the background?

I've already checked if this might be a SW thing, but at least one router where the numbers are probably correct, has the same SW version as the one mentioned above.

Please let me know if there is anything that I can do to troubleshoot this.

**Comment by respawner** [comment]
No sadly there is no debug possible for NAPALM action for now.

I'll try to do this as soon as possible since that could be useful.

I'll commit the patch that I'm currently polishing so you'll be able to re-test the feature. Then I'll try to make NAPALM related functions a bit more verbose by logging what they do.

**Comment by respawner** [comment]
The fix for the number of imported BGP sessions has been commited in 04e199e. Could you please test it once again to see if the displayed count is correct? Thanks.

**Comment by FredNeuberger** [comment]
Still got "Imported 4 autonomous systems" on the same router from the example above, even though the number of "Autonomous Systems" stayed the same.

I've then deleted the IXP and rediscovered everything. Now it says:

Imported 4 autonomous systems
Imported 18 peering sessions 

So at least from a sessions point of view, the number displayed is matching the number of actual sessions being visible.

**Comment by FredNeuberger** [comment]
Is this being logged into /opt/peering-manager/logs/peering-manager.log ?

Got this message now:
2018-03-07 13:24:43 | DEBUG | found XXX bgp neighbors in global vrf on X.X.X.X

This is a step into the right direction. Would be cool if I could see the exact output NAPALM is generating. Maybe with a verbose debugging that can be turned on and off?


In regards to the 4 ASN it says it has added: They are both not in PeeringDB and they are not being added to the list of sessions.

Would it be an idea to check for PDB entry first and then generate the message that # of ASN have been added?

**Comment by respawner** [comment]
> This is a step into the right direction. Would be cool if I could see the exact output NAPALM is generating. Maybe with a verbose debugging that can be turned on and off?

I'll see what I can do to do some kind of raw debugging.

> In regards to the 4 ASN it says it has added: They are both not in PeeringDB and they are not being added to the list of sessions.
>
> Would it be an idea to check for PDB entry first and then generate the message that # of ASN have been added?

In theory this case should already been handled. But I'll take another look at the code to see if there are any mistakes in it.

**Comment by FredNeuberger** [comment]
I've checked the routers where the imported session are sigificantly smaller that what it should be and it looks like that if VRFs are being returned by NAPALM (including the GLOBAL one), Peering-Manager has a problem with that.

Funny thing is, we have a router that has VRFs configured, but they are not being returned by NAPALM when querying for BGP neighbors.

Not sure how to proceed here.

**Comment by FredNeuberger** [comment]
So the questions are:

- How is PM currently handling the output of NAPALM
- Does it make sense care about VRFs, or could PM just ignore that stuff and concentrate on GLOBAL?
- Anything else I can do to test/provide feedback/output?

- Should I maybe open an issue with the NAPALM guys because of that crazy behavior? Not sure why it would sometimes have VRFs in the output and sometimes not, even though they are clearly configured.

**Comment by respawner** [comment]
> How is PM currently handling the output of NAPALM

PM is supposed to iterate over all VRFs and their respective peers. So peering sessions that are imported can inside or out a VRF.

> Does it make sense care about VRFs, or could PM just ignore that stuff and concentrate on GLOBAL?

I think that it can make sense for PM to import sessions configured inside VRFs. I have known use cases where people use VRFs for peering sessions.

> Anything else I can do to test/provide feedback/output?

Could you provide a NAPALM output which with there is an issue importing sessions? You can modify the data to avoid leaking sensible details if you want. The idea is just to get data even with not the real IPs, ASNs, etc to investigate.

> Should I maybe open an issue with the NAPALM guys because of that crazy behavior? Not sure why it would sometimes have VRFs in the output and sometimes not, even though they are clearly configured.

Do not bother reporting the issue to the NAPALM guys, at least not yet.

What I will do is (when I'll have some data) to write test cases to see where the issue is and have a clear idea of what the issue is. Is it related to PM or NAPALM. If it is due to PM, I'll find the way to fix it. If it is due to NAPALM, I'll open an issue on their github so they can investigate. I have already found a bug and reported it to them.

**Comment by FredNeuberger** [comment]
That looks very good so far.

Deleted all sessions on both IXPs and re-imported them. No issues so far.
I will check if the imported sessions are matching the ones configured later today.

Thank you very much.
