### ISSUE TITLE
Can't remove a template from an IX

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#131]
### Environment
* Python version:  3.5.3
* Peering Manager version:  master

### Steps to Reproduce

http://peeringmanager/internet-exchanges/{ix_slug}/edit/ -> Deployment -> Configuration template

### Expected Behavior

Since per-IX configuration templates are being deprecated in favour of per-router configuration templates, one would need to remove templates previously applied to IXs to become compliant.

### Observed Behavior

There is no ability to remove a template from an IX.

**Comment by respawner** [comment]
Since 46403cb you should be able to use the clear mechanism of the select element to remove the selected value and submit the form to save the `null` value thus removing the template reference from the IX.

Can you try that and let me know if this work?

**Comment by jlixfeld** [comment]
Yes, that worked.  Thanks.
