### ISSUE TITLE
CSRF Token

### ISSUE THREAD

**Issue by jjavierweb** [respawner/peering-manager#132]
Hi, I have just installed the peering-manager following the instruction on the documentation and I keep getting the csrf token issue every time I try to login 
Forbidden (403)
CSRF verification failed. Request aborted.

Help
Reason given for failure:

    Referer checking failed - https://xxxxxxxxx.com/login/?next=/login/ does not match any trusted origins.
    
In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django's CSRF mechanism has not been used correctly. For POST forms, you need to ensure:

Your browser is accepting cookies.
The view function passes a request to the template's render method.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.
You're seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting.

I tried moving the location of the {% csrf_token %} on the form but it is not working for me 
I tried a couple more things from doing some research and still, nothing worked 
Please help
Thanks,

**Comment by 2bithacker** [comment]
I ran into this recently as well, you probably need to set [`CSRF_TRUSTED_ORIGINS`](https://docs.djangoproject.com/en/2.2/ref/settings/#csrf-trusted-origins).

In my case, I just set it to be the same as `ALLOWED_HOSTS`. In `settings.py`:

```
CSRF_TRUSTED_ORIGINS = ALLOWED_HOSTS
```

**Comment by respawner** [comment]
Maybe we should add this as a default in `settings.py`?

**Comment by jjavierweb** [comment]
Thanks, this worked, I think it would be better for those like me that don't know django in and outs
Thanks again

**Comment by 2bithacker** [comment]
I don't think it would hurt to have it as the default. I know that's what [NetBox does](https://github.com/digitalocean/netbox/blob/f9dba8a75c82b36d7b081419e5f988c2462f41de/netbox/netbox/settings.py#L78).
