### ISSUE TITLE
Enhancement for storage of session password

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#134]
### Environment
* Python version:  3.5.3
* Peering Manager version:  master

I did not accurately convey my original thoughts around this in #62 

My intention was to suggest that one could enter an encrypted or an unencrypted password into the field and have it remain in the original format that it was entered in.

It seems that any password that is entered is considered unencrypted, so it is encrypted when it is saved, stored in the database encrypted, but the unencrypted password is no longer retrievable.

### Proposed Functionality

If a password is entered into the password field as clear text, it should be retrievable some how in it's original clear text format.

If a password is entered into the password field as an encrypted string, then no additional functionality is required.

### Use Case

A bunch of sessions are configured with passwords, and the router is later switched to a different vendor that uses a different method of password encryption.  The original clear text passwords would be required so they could be re-encrypted when Peering Manager creates the configuration for the new hardware.

### External Dependencies

Would need a way to prevent the clear-text passwords from being re-encrypted on each configuration deployment (and causing the issue that led to #62) but also preserve the original, clear-text password for future retrieval.

**Comment by respawner** [comment]
What we could imagine is to never touch the user input. Encrypted or not the password will then be stored as it is. Then we could solve the encryption issue at the router's template level.

Basically if the user wants passwords to be encrypted before sending them to the router, we can introduce a new Jinja2 filter called `encrypt`, for instance, that would then encrypt passwords when generating the configuration. The called to the Jinja2 filter inside the template would look like:

```
authentication-key "{{ session.password | encrypt }}";
```

With this we could recommend to any users to enter passwords in clear text and then let Peering Manager encrypt them when deploying if it was asked to do so.

That said this leads to another issue. With this the password will be re-encrypted at each configuration generation and encrypted strings have a good chance of being different. This means that Peering Manager will decide that the configuration has changed compared to the running configuration on the device.

To solve the re-encryption issue we would have to introduce another field to store the encrypted password and avoid it to be re-encrypted every time. This field would have to be reset in case of router vendor change though.
