### ISSUE TITLE
Change Default REST API Pagination Module

### ISSUE THREAD

**Issue by 2bithacker** [respawner/peering-manager#137]
### Environment
* Python version:  3.6.7
* Peering Manager version:  master

### Proposed Functionality

Proposing the REST API pagination module in `settings.py` be changed from `PageNumberPagination` to `LimitOffsetPagination`.

### Use Case

For simple-minded clients (such as using  `curl` in a shell script) it is difficult to deal with the page number based pagination as it offers no controls to the client as to how many items are included in the request.

`LimitOffsetPagination` would allow clients to include a `limit` parameter in the request, which could be set large enough to avoid pagination.

This makes it easier to write clients, however it does put additional load on the server as it has to be able to deal with larger result sets. I think the impact is minimal enough for most installations that the benefit outweighs the cost.

### External Dependencies

No new dependencies, `LimitOffsetPagination` is included with django-rest-framework.

**Comment by respawner** [comment]
PR merged see b377061.
