### ISSUE TITLE
Creating peering-sessions via API raises error

### ISSUE THREAD

**Issue by VilhelmPrytz** [respawner/peering-manager#146]
### Environment
* Python version:  3.5.3
* Peering Manager version:  master

### Steps to Reproduce
Send a POST request to the API endpoint `/api/peering/internet-exchange-peering-sessions/` with the appropriate payload.

Example payload:
```
{
        "autonomous_system": {
            "asn": 0000
        },
        "internet_exchange": {
            "name": "name",
            "slug": "slug"
        },
        "ip_address": "8.8.8.8",
        "enabled": true,
        "is_route_server": false
}
```
### Expected Behavior
If all required values are set the expected behavior would be a successful request.

### Observed Behavior
API returns `Primary key must be an integer` for `autonomous_system` and `internet_exchange`.

**Comment by VilhelmPrytz** [comment]
Nevermind, this was a malformed request. You cannot specify the ASn in this request, you have to specify the id of the ASn that already exists within the peering-manager database. Maybe unclear documentation?

**Comment by jlixfeld** [comment]
@VilhelmPrytz would you mind posting the working payload and script snippets.  Someone (waves hand) may find that information useful, and it would serve as good seeding for API usage documentation as it grows.

**Comment by VilhelmPrytz** [comment]
Sure thing!

So I thought peering-manager would automatically create the AS by defining it per my initial request. I also thought that I could define the slug of the IX I wanted to create the session for.

It turns out you have to create the AS before you perform this request, and that you have to know the ID of both the AS and the IX to add a session to them.

The ´autonomous_system` and `internet_exchange` have to be defined like this:
```"autonomous_system": 0,
internet_exchange: 0,```

... where the numbers are the ID's of the ASN and IX respectively (IDs that they have within the peering-manager database).

You can retrieve information about a specific AS using the following endpoint `/api/peering/autonomous-systems?asn={{ asn }}` for example (`id`will be the first variable).
