### ISSUE TITLE
Tagging system for IXPs

### ISSUE THREAD

**Issue by VilhelmPrytz** [respawner/peering-manager#150]
### Environment
* Python version:  3.5.3
* Peering Manager version:  master

### Proposed Functionality
Add a tagging system to IXPs (or custom field?) to add the ability to group Internet Exchange Points together.

### Use Case
Useful when you have several IXPs that are on the same site (needs to be grouped together).

Perhaps it could be implemented in other areas of peering-manager as well?

**Comment by respawner** [comment]
Introducing a tagging system could be nice. I'd like to hear about use cases for that because I'm curious. To avoid spending too much time developing such thing it could be a good idea to introduce a new dependency like [django-taggit](https://github.com/jazzband/django-taggit).

**Comment by VilhelmPrytz** [comment]
Yes, using a dependency seems like a good idea!

**Comment by VilhelmPrytz** [comment]
Any updates regarding this?

**Comment by respawner** [comment]
Feature implemented as of 84914fe.
