### ISSUE TITLE
Changes made to IX Peering Session are not persistent

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#153]
### Environment
* Python version:  3.5.3
* Peering Manager version:  master

### Steps to Reproduce

1. http://peeringmanager/internet-exchanges/{{ ixp }}/peering-sessions/
2. Check box next to session of interest
3. Edit Selected
4. Make some change
5. Click Apply

### Expected Behavior

Changes made should be persistent.

### Observed Behavior

Goto step 2 in Steps to Reproduce, observe the settings set previously are not preserved.

**Comment by respawner** [comment]
It looks like I cannot reproduce the issue as of commit 4a6c538.

Did you notice some specific fields not being saved or is it affecting all of them?

**Comment by jlixfeld** [comment]
So it would save enabled or route server, but it wouldn't display the settings if you edited the settings for that session again.

It wouldn't save import or export routing policies at all.

I'm getting ready to upgrade my lab instance to post 4a6c538 so we'll see what happens then.

**Comment by respawner** [comment]
It looks to be working for though I found some possible behavior improvements to be made. Field states do not reflect their actual values. This could be confusing for user. Moreover, lets say some sessions have routing policies set. If we'd like to remove them using the bulk edit we need to select a value from the dropdown then remove it using the little cross. Adding a checkbox "set empty" could be useful there.

So field values are actually saved by the behavior is to be fixed.

**Comment by jlixfeld** [comment]
> It looks to be working for though I found some possible behavior improvements to be made. Field states do not reflect their actual values. This could be confusing for user.

I upgraded yesterday and do indeed see the settings now.
