### ISSUE TITLE
Changelog Visualization issue

### ISSUE THREAD

**Issue by jjavierweb** [respawner/peering-manager#158]
### Environment
* Python version:  3.6.3
* Peering Manager version:  0.99

### Steps to Reproduce
Log into the system and make a log of changes

### Expected Behavior
scroll  changelogs and they will stay inside the container

### Observed Behavior
Changelog list goes beyond the container until you get to the end of the list
![image](https://user-images.githubusercontent.com/12855611/61893351-7d001280-aed3-11e9-9e4f-b0c4b665003a.png)

th

**Comment by respawner** [comment]
I confirm that this UI bug can be seen with several browsers running on different OSes. I did find the CSS trick yet so if someone has any clues or even a fix I'll be happy to talk about them.

**Comment by jjavierweb** [comment]
I'll be happy to help if that's possible

**Comment by VilhelmPrytz** [comment]
I also noticed this issue, seems to be persistent on all OSes and browsers. CSS related?

**Comment by jjavierweb** [comment]
So I have done more testing, and it seems that this problem only happens on windows computers, not sure about linux yet, on mac this works fine without issues

**Comment by respawner** [comment]
I have the issue on macOS with Chrome but not with Safari.

**Comment by VilhelmPrytz** [comment]
I have the same as @respawner, also an issue in Firefox on both macOS and Linux.
