### ISSUE TITLE
Use IPv4 and IPv6 reserved for documentation

### ISSUE THREAD

**Issue by respawner** [respawner/peering-manager#159]
### Proposed Changes

Use IPv4 and IPv6 reserved for documentation inside the documentation of this project as well as in the tests.

**Comment by respawner** [comment]
This could be an issue with an easy fix. So if anybody wants to contribute this is a good issue to start.

**Comment by charlesmonson** [comment]
> This could be an issue with an easy fix. So if anybody wants to contribute this is a good issue to start.

I can take a crack at this. The only place I see any IPv4 currently is in the tests.

I'll look through the documentation to see if there is anywhere that would make sense to add some IP examples.
