### ISSUE TITLE
JUNOS Exception checking when committing

### ISSUE THREAD

**Issue by FredNeuberger** [respawner/peering-manager#16]
Tried my first config commit today and found something that could be improved.

Basically I forgot to configure router-id and autonomous-system on my lab router.
GUI said "Configuration saved, but on the router nothing was applied.
napalm.log just shows:
2018-03-21 18:19:08 | DEBUG | unable to merge configuration on x.x.x.x

After copypasting from the guy, it was obvious:

[edit protocols]
  'bgp'
    Error in neighbor 1.1.1.1 of group ipv4-nyiix-test:
must define local autonomous system when enabling BGP
error: configuration check-out failed

Would be nice if this is being shown in the GUI somehow.
What do you think about additionally checking if the config is really in place?

Let me know if you need something else or want me to re-test

**Comment by FredNeuberger** [comment]
I've checked the case from above again and now I see a red button "Config not saved".

I also tested what happens if the config is already locked (manually through the CLI with edit exclusive):
"No configuration differences found.
The router may be up-to-date or unreachable."

**Comment by respawner** [comment]
Nice, you should have a log to tell you what did go wrong as well.

I'm aware of the issue when the config is locked. I did not find a way to know why the configuration does not find any differences. It can be due to several cases, I'll add a hint in the returned message to give more clues to the user.

**Comment by FredNeuberger** [comment]
018-03-23 13:15:25 | DEBUG | unable to merge configuration on x.x.x.x error "LockError(severity: error, bad_element: None, message: configuration database locked by:
  someuser terminal pts/0 (pid 4746) on since 2018-03-23 12:14:23 UTC
      exclusive [edit])"

**Comment by respawner** [comment]
Interesting. Then there should be a way to report that specific fault to the user. Thanks for the feedback 👍
