### ISSUE TITLE
Multiple routers per Exchange

### ISSUE THREAD

**Issue by pstanczak** [respawner/peering-manager#17]
Currently, an Exchange can have only one router.  Exchanges should have the ability to have multiple routers.

**Comment by FredNeuberger** [comment]
Hi,
Works for us currently. You just need to make sure to give the IXP an unique name (I renamed both name and slug) when importing from PDB.

Cheers

**Comment by respawner** [comment]
What we call an IX in Peering Manager is more like a IX connection. By that it means that it can only have one IPv6 and one IPv4 address. Therefore you can only link one router. If you have several routers connected to the same IX, you can create multiple IX inside Peering Manager but each slug **must** be unique.

Maybe this paradigm is not clear enough and need to be documented?

**Comment by respawner** [comment]
Documentation added but to be improved, see [here](http://peering-manager.readthedocs.io/en/latest/man/).
