### ISSUE TITLE
Multiple ASN's?

### ISSUE THREAD

**Issue by smaxx1337** [respawner/peering-manager#170]
Hello,

we are currently operating with more than one ASN. The config file however only has an entry for one ASN. Can we just add more ASN's, or is peering-manager not able to do this?

**Comment by ggiesen** [comment]
You currently have to run one instance per ASN (I'm currently running 4 instances). I believe support for multiple ASNs is planned but not defined timeline

**Comment by smaxx1337** [comment]
Okay, is it somehow possible to run a instance in a directory? If yes, how? I have tried something with Apache VirtualHosts but it's giving me a error because the Alias gets overwritten. If you have any documentation or tutorial for this, please provide me one. Thanks

**Comment by VilhelmPrytz** [comment]
> Okay, is it somehow possible to run a instance in a directory? If yes, how? I have tried something with Apache VirtualHosts but it's giving me a error because the Alias gets overwritten. If you have any documentation or tutorial for this, please provide me one. Thanks
> 
> //edit, to make it more clear:
> I would like to have peering-manager1 in http://example.com/asn1/ and peering-manager2 in http://example.com/asn2/. Is this possible?

Not sure how you do this using Apache, but using Nginx it's fairly straight-forward. Just make sure you're installations are separated.

**Comment by respawner** [comment]
You'll have to change the `BASE_PATH` option un the configuration to match your virtual host's. `BASE_PATH = asn1/` for instance.

**Comment by smaxx1337** [comment]
Hmm, I tried doing this in Apache but because of the
`alias /static /opt/static/` it gives me a error that the second alias gets overwritten because it exists.
Can you somehow give me a direction in doing this in nginx? @VilhelmPrytz

**Comment by VilhelmPrytz** [comment]
@smaxx1337 Setup two installations of peering-manager at two different paths, and two supervisor services for each instance. Create two `location` blocks in your Nginx configuration, pointing to each service. I haven't tried this myself, but it should work as long as you make sure to use different `BASE_PATH`s as @respawner mentioned.

**Comment by smaxx1337** [comment]
So i got asn1/ somehow working Apache, but without CSS. I put Django into debug mode and it told me that it cant find the /static directory, but its there. 
Here is my apache config:
```
<VirtualHost *:80>
  ProxyPreserveHost On
  ServerName peering.example.com
  Alias /static /opt/asn1/static

  <Directory /opt/asn1/static>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Require all granted
  </Directory>

  <Location /static>
    ProxyPass !
  </Location>

  ProxyPass / http://127.0.0.1:8001/
  ProxyPassReverse / http://127.0.0.1:8001/
</VirtualHost>

```


Here is the configuration.py:
```
# This is a list of valid fully-qualified domain names (FQDNs) for this server.
# The server will not permit write access to the server via any other
# hostnames. The first FQDN in the list will be treated as the preferred name.
#
# Example: ALLOWED_HOSTS = ['peering.example.com', 'peering.internal.local']
ALLOWED_HOSTS = ["xxx", "xxx"]

# Must be unique to each setup (CHANGE IT!).
SECRET_KEY = "xxx"

# Base URL path if accessing Peering Manager within a directory.
BASE_PATH = "asn1/"

# Time zone to use for date.
TIME_ZONE = "Europe/Paris"

DEBUG = "TRUE"

# Autonomous System number
MY_ASN = xxx

# PostgreSQL database configuration
DATABASE = {
    "NAME": "peering_manager",  # Database name
    "USER": "peering_manager",  # PostgreSQL username
    "PASSWORD": "xxxx",  # PostgreSQL password
    "HOST": "localhost",  # Database server
    "PORT": "",  # Database port (leave blank for default)
}

```

Suggestion: It would be cool to have a section in the documentation that helps you if you need to setup multiple instances of peering-manager, especially the apache / nginx config part is what tricks me.

**Comment by VilhelmPrytz** [comment]
What is your supervisor configuration?

**Comment by smaxx1337** [comment]
```
[program:peering-manager]
directory = /opt/asn1/
command = gunicorn -c /opt/asn1/gunicorn_config.py peering_manager.wsgi
user = apache
```

gunicorn_config.py:
```
command = '/bin/gunicorn'
pythonpath = '/opt/asn1/'
bind = '127.0.0.1:8001'
workers = 4
user = 'apache'

```

**Comment by VilhelmPrytz** [comment]
Put `pythonpath` above `command` in `gunicorn_config.py`.

**Comment by smaxx1337** [comment]
Well, I did that but it changed nothing. What does it have to do with the CSS? 🤔 
Sorry if I sound stupid.

**Comment by respawner** [comment]
Did you collect the static files as described [here](https://peering-manager.readthedocs.io/en/latest/setup/2-peering-manager/)?

**Comment by smaxx1337** [comment]
At the installation of peering-manager, yes, but after moving everything into the asn1/ directory, no. But i've run it and here's the output:
`0 static files copied to '/opt/asn1/static', 295 unmodified.`

**Comment by VilhelmPrytz** [comment]
> Well, I did that but it changed nothing. What does it have to do with the CSS / reachability of the /static directory? 
> Sorry if I sound stupid.

When I read that your Django installation couldn't find the `static` directory, I remembered having the same issue. For me, it got solved when I moved the `pythonpath` to be above `command` and then restarting. Seems like a silly fix, unsure if it actually did something.

**Comment by smaxx1337** [comment]
I think it really has something to do with the apache config. Do you have a example nginx config file for me? Because in my /opt/asn1/ directory, there is a static folder etc, everything. But in 80, there isn't. 
```
Failed to load resource: the server responded with a status of 404 (Not Found)
toolbar.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by smaxx1337** [comment]
Well, I tried creating a nginx config file on my own but failed miserably, the static files are still not loading 😆 
```

server {
    listen 80 default_server;

    server_name peering.example.comblabla;

    location /static/ {
        alias /opt/asn1/static/;
    }

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        if (!-f $request_filename) {
            proxy_pass http://127.0.0.1:8001;
            break;
        }
    }
}
```

**Comment by ggiesen** [comment]
Here's my configs for your reference (CentOS 7):

/etc/httpd/conf.d/peering-manager-asXXXXX:
``ProxyPreserveHost On
``
``Alias /peering/asXXXXX/static /opt/peering-manager-asXXXXX/static
``
``<Directory /opt/peering-manager-asXXXXX/static>
``  Options Indexes FollowSymLinks MultiViews
``  AllowOverride None
``  Require all granted
``</Directory>
``
``<Location /peering/asXXXXX/static>
``  ProxyPass !
``</Location>
``
``
``ProxyPass /peering/asXXXXX http://127.0.0.1:8001/peering/asXXXXX timeout=360
``ProxyPassReverse /peering/asXXXXX http://127.0.0.1:8001/peering/asXXXXX timeout=360

/etc/httpd/conf.d/peering-manager-asYYYYY:
``ProxyPreserveHost On
``
``Alias /peering/asYYYYY/static /opt/peering-manager-asYYYYY/static
``
``<Directory /opt/peering-manager-asYYYYY/static>
``  Options Indexes FollowSymLinks MultiViews
``  AllowOverride None
``  Require all granted
``</Directory>
``
``<Location /peering/asYYYYY/static>
``  ProxyPass !
``</Location>
``
``
``ProxyPass /peering/asYYYYY http://127.0.0.1:8002/peering/asYYYYY timeout=360
``ProxyPassReverse /peering/asYYYYY http://127.0.0.1:8002/peering/asYYYYY timeout=360


/etc/httpd/conf.d/peering-manager-asZZZZZ:
``ProxyPreserveHost On
``
``Alias /peering/asZZZZZ/static /opt/peering-manager-asZZZZZ/static
``
``<Directory /opt/peering-manager-asZZZZZ/static>
``  Options Indexes FollowSymLinks MultiViews
``  AllowOverride None
``  Require all granted
``</Directory>
``
``<Location /peering/asZZZZZ/static>
``  ProxyPass !
``</Location>
``
``
``ProxyPass /peering/asZZZZZ http://127.0.0.1:8003/peering/asZZZZZ timeout=360
``ProxyPassReverse /peering/asZZZZZ http://127.0.0.1:8003/peering/asZZZZZ timeout=360


/etc/supervisord.d/peering-manager-asXXXXX.ini
``command = /usr/local/bin/gunicorn -c /opt/peering-manager-asXXXXX/gunicorn_config.py peering_manager.wsgi
``directory = /opt/peering-manager-asXXXXX/
``user = apache


/etc/supervisord.d/peering-manager-asYYYYY.ini
``command = /usr/local/bin/gunicorn -c /opt/peering-manager-asYYYYY/gunicorn_config.py peering_manager.wsgi
``directory = /opt/peering-manager-asYYYYY/
``user = apache


/etc/supervisord.d/peering-manager-asZZZZZ.ini
``command = /usr/local/bin/gunicorn -c /opt/peering-manager-asZZZZZ/gunicorn_config.py peering_manager.wsgi
``directory = /opt/peering-manager-asZZZZZ/
``user = apache


/opt/peering-manager-asXXXXX/gunicorn_config.py
``command = '/usr/local/bin/gunicorn'
``pythonpath = '/opt/peering-manager-asXXXXX'
``bind = '127.0.0.1:8001'
``workers = 4
``user = 'apache'
``timeout = 300


/opt/peering-manager-asYYYYY/gunicorn_config.py
``command = '/usr/local/bin/gunicorn'
``pythonpath = '/opt/peering-manager-asYYYYY'
``bind = '127.0.0.1:8002'
``workers = 4
``user = 'apache'
``timeout = 300


/opt/peering-manager-asZZZZZ/gunicorn_config.py
``command = '/usr/local/bin/gunicorn'
``pythonpath = '/opt/peering-manager-asZZZZZ'
``bind = '127.0.0.1:8003'
``workers = 4
``user = 'apache'
``timeout = 300

**Comment by smaxx1337** [comment]
Wow, it works! thank you very much :)
We should maybe make a entry in the documentation, if you want to make multiple instances of peering-manager, then do X Y Z in /etc/httpd/conf.d/ or link to this issue here. Thanks to everyone who helped me.

**Comment by ggiesen** [comment]
The only issue I have with that config is that you can only be logged into one instance at a time (when you log into another instance, you are logged out of the first one). Not sure if it's Apache-related or Peering Manager-related (I suspect the latter). All instances are using unique values for SECRET_KEY in configuration.py.

**Comment by ggiesen** [comment]
Note I have updated my previous post to add a new config stanza containing ProxyPassReverseCookiePath to deal with the issue of being logged into more than one instance at a time.

> 
> 
> Here's my configs for your reference (CentOS 7):
> 
> /etc/httpd/conf.d/peering-manager-asXXXXX:
> 
> ```
> ProxyPreserveHost On
> 
> Alias /peering/asXXXXX/static /opt/peering-manager-asXXXXX/static
> 
> <Directory /opt/peering-manager-asXXXXX/static>
>   Options Indexes FollowSymLinks MultiViews
>   AllowOverride None
>   Require all granted
> </Directory>
> 
> <Location /peering/asXXXXX/static>
>   ProxyPass !
> </Location>
> 
> <Location /peering/asXXXXX>
>   ProxyPassReverseCookiePath / /peering/asXXXXX
> </Location>
> 
> ProxyPass /peering/asXXXXX http://127.0.0.1:8001/peering/asXXXXX timeout=360
> ProxyPassReverse /peering/asXXXXX http://127.0.0.1:8001/peering/asXXXXX timeout=360
> ```
> 
> /etc/httpd/conf.d/peering-manager-asYYYYY:
> 
> ```
> ProxyPreserveHost On
> 
> Alias /peering/asYYYYY/static /opt/peering-manager-asYYYYY/static
> 
> <Directory /opt/peering-manager-asYYYYY/static>
>   Options Indexes FollowSymLinks MultiViews
>   AllowOverride None
>   Require all granted
> </Directory>
> 
> <Location /peering/asYYYYY/static>
>   ProxyPass !
> </Location>
> 
> <Location /peering/asYYYYY>
>   ProxyPassReverseCookiePath / /peering/asYYYYY
> </Location>
> 
> ProxyPass /peering/asYYYYY http://127.0.0.1:8002/peering/asYYYYY timeout=360
> ProxyPassReverse /peering/asYYYYY http://127.0.0.1:8002/peering/asYYYYY timeout=360
> ```
> 
> /etc/httpd/conf.d/peering-manager-asZZZZZ:
> 
> ```
> ProxyPreserveHost On
> 
> Alias /peering/asZZZZZ/static /opt/peering-manager-asZZZZZ/static
> 
> <Directory /opt/peering-manager-asZZZZZ/static>
>   Options Indexes FollowSymLinks MultiViews
>   AllowOverride None
>   Require all granted
> </Directory>
> 
> <Location /peering/asZZZZZ/static>
>   ProxyPass !
> </Location>
> 
> <Location /peering/asZZZZZ>
>   ProxyPassReverseCookiePath / /peering/asZZZZZ
> </Location>
> 
> ProxyPass /peering/asZZZZZ http://127.0.0.1:8003/peering/asZZZZZ timeout=360
> ProxyPassReverse /peering/asZZZZZ http://127.0.0.1:8003/peering/asZZZZZ timeout=360
> ```
> 
> /etc/supervisord.d/peering-manager-asXXXXX.ini:
> 
> ```
> command = /usr/local/bin/gunicorn -c /opt/peering-manager-asXXXXX/gunicorn_config.py peering_manager.wsgi
> directory = /opt/peering-manager-asXXXXX/
> user = apache
> ```
> 
> /etc/supervisord.d/peering-manager-asYYYYY.ini:
> 
> ```
> command = /usr/local/bin/gunicorn -c /opt/peering-manager-asYYYYY/gunicorn_config.py peering_manager.wsgi
> directory = /opt/peering-manager-asYYYYY/
> user = apache
> ```
> 
> /etc/supervisord.d/peering-manager-asZZZZZ.ini:
> 
> ```
> command = /usr/local/bin/gunicorn -c /opt/peering-manager-asZZZZZ/gunicorn_config.py peering_manager.wsgi
> directory = /opt/peering-manager-asZZZZZ/
> user = apache
> ```
> 
> /opt/peering-manager-asXXXXX/gunicorn_config.py:
> 
> ```
> command = '/usr/local/bin/gunicorn'
> pythonpath = '/opt/peering-manager-asXXXXX'
> bind = '127.0.0.1:8001'
> workers = 4
> user = 'apache'
> timeout = 300
> ```
> 
> /opt/peering-manager-asYYYYY/gunicorn_config.py:
> 
> ```
> command = '/usr/local/bin/gunicorn'
> pythonpath = '/opt/peering-manager-asYYYYY'
> bind = '127.0.0.1:8002'
> workers = 4
> user = 'apache'
> timeout = 300
> ```
> 
> /opt/peering-manager-asZZZZZ/gunicorn_config.py:
> 
> ```
> command = '/usr/local/bin/gunicorn'
> pythonpath = '/opt/peering-manager-asZZZZZ'
> bind = '127.0.0.1:8003'
> workers = 4
> user = 'apache'
> timeout = 300
> ```
