### ISSUE TITLE
E-Mail settings?

### ISSUE THREAD

**Issue by smaxx1337** [respawner/peering-manager#172]
Hello,

in the documentation there is no entry for e-mails or such thing, so I guess I have to ask here:
In the "Templates" section you can create a E-Mail template with Jinja2. But what can I do with it? Where i can see the "filled out" template? How does it work? I am kinda new to this. Or is this a feature that is not fully implemented yet?

Thanks for any answer,
smaxxx

**Comment by respawner** [comment]
This feature is not yet implemented. Refer to the issues already opened about this.
