### ISSUE TITLE
BGPQ3 documentation

### ISSUE THREAD

**Issue by smaxx1337** [respawner/peering-manager#173]
Hello,

is there any Peering-Manager with BGPQ3 documentation where I can look further into? I have set it up in the configuration.py (idk if thats correct) but how do I continue from there? I guess set it into the template, but is there any variable list for the BGPQ3 things? Maybe I set the configuration wrong:
```
BGPQ3_PATH = "/usr/bin/bgpq3"
BGPQ3_HOST = "rr.ntt.net"
BGPQ3_SOURCES = "RIPE","APNIC","AFRINIC","ARIN","NTTCOM","ALTDB","BBOI","BELL","JPIRR","LEVEL3","RADB","RGNET","SAVVIS,TC"
BGPQ3_ARGS = {"ipv6": ["-r", "16", "-R", "48"], "ipv4": ["-r", "8", "-R", "24"]}

```

Thanks for any help.

**Comment by respawner** [comment]
A `prefix_list` function, which uses BGPQ3, is available in template. See [doc](https://peering-manager.readthedocs.io/en/latest/templates/).

If you want to discuss about this please jojn the `#peering-manager` channel on NetworkToCode Slack to avoid opening issues that are used for bugs, feature requests and improvements.
