### ISSUE TITLE
Assign multiple routers if wanted to a IX

### ISSUE THREAD

**Issue by smaxx1337** [respawner/peering-manager#183]
Hello, we would like to assign multiple routers to a IX. How about a form that when you press a "+" on the right side it creates another form where you can assign the router?

Like this (some pretty bad pictures):
![router_choosing](https://user-images.githubusercontent.com/8495515/69133229-de1ca900-0ab5-11ea-8c8f-9664f851a68b.PNG)

And if someone presses on the blue plus:
![router_2](https://user-images.githubusercontent.com/8495515/69133242-e4128a00-0ab5-11ea-9cbb-1ccb54dc597c.jpg)

We currently have a fake router to create something for a different purpose, not a actual configuration. But changing the router assignment in the IX everytime can get annoying :D

**Comment by respawner** [comment]
Connecting multiple routers to one IX is compatible with the way that the IX / router relationship was designed. One IX means one connection with one IP of each family. Assigning one router temporarily to an IX to then change it, and to do that quite often in a production environment, looks like a very special use-case. I'd like not to rework the whole IX/router relationship just for this single use-case.
