### ISSUE TITLE
Modularize device interaction functions to make it extensible

### ISSUE THREAD

**Issue by gl** [respawner/peering-manager#184]
Network Operators may have dedicated IT stacks to interact with their hardware, using napalm or netbox (that in turn uses napalm) might not be an option in that case.

To make it doable for operators to integrate peering-manager in their IT stack, it is necessary to abstract the interaction functions in models.py and modularize the napalm and netbox integrations.

**Comment by respawner** [comment]
Do you have any particular ideas to improve the way Peering Manager receives/sends data from/to a device? Would exposing API endpoints be enough (such as `/api/routers/{{ id }}/configuration/`) be enough?

**Comment by gl** [comment]
It could be a good idea to have configuration per router, I was more
thinking of the model calling the right module (and hence importing the
right get_bgp... functions)

An external developer could then create a separate module with the same
functions to talk to another device abstraction API/program.

E.g., in my case I need to send rest requests to the in-house network
abstraction tool to get the bgp information back, in JSON format, but
currently, since device interaction is hardcoded in the models, I can't
overload the functions.

>

**Comment by respawner** [comment]
This could be a job for a web-hook system maybe, sending JSON hooks to given endpoints when some actions are triggered.
