### ISSUE TITLE
Configuration tab is incorrect

### ISSUE THREAD

**Issue by jnikoletich** [respawner/peering-manager#19]
Hi,

When clicking on the configuration tab in PM, the configuration comes up empty.

Only the group and slug name (without the ipv4 and ipv6) is shown. 

This happened after the last update

<img width="915" alt="exash" src="https://user-images.githubusercontent.com/29226372/39656658-5a28d472-4fb6-11e8-9a4e-34adfbed178b.PNG">
<img width="928" alt="template" src="https://user-images.githubusercontent.com/29226372/39656659-5a414df4-4fb6-11e8-8a16-9e68ce40ca79.PNG">

**Comment by respawner** [comment]
The templating variables have been redefined recently in this [commit](https://github.com/respawner/peering-manager/commit/0f0cec2e225f90f68627214481262a7bb9ca1863). So you should probably change the template you are currently using. You can get the details and a template example [here](http://peering-manager.readthedocs.io/en/latest/config-template/).

**Comment by respawner** [comment]
Closing, due to inactivity.
