### ISSUE TITLE
Revamp the homepage

### ISSUE THREAD

**Issue by respawner** [respawner/peering-manager#20]
The current homepage is quite useless for now except for the history/logs side.

We should revamp it to make it useful and display meaningful content for the users.

I'm looking for ideas about what to display and maybe how on this page.

**Comment by jnikoletich** [comment]
I would say more about stats would be great. Like most connected IX, total peer routes, highest peer routes by AS, current down peers, etc.

**Comment by respawner** [comment]
Will be addressed in #81.
