### ISSUE TITLE
Bulk edit - setting route server / enabled to NO is not working

### ISSUE THREAD

**Issue by rgarcia89** [respawner/peering-manager#204]
### Environment
* Python version: 3.8.1
* Peering Manager version:  1.1.0

### Steps to Reproduce
Select multiple sessions and set them on the right menu to enabled no.
Apply the change - you will see nothing is happening.

### Expected Behavior
Sessions should change to disabled state.

### Observed Behavior
Nothing

**Comment by respawner** [comment]
This issue has been silently fixed in a4fa5f7 so the fix will be available in the next release.

**Comment by rgarcia89** [comment]
Thanks - do you already know when the next release will be available?

**Comment by respawner** [comment]
When it's ready. I need to finish some heavy work on the unit test part and merge the cache feature (using redis). `1.2.0` should be released just after, if no outstanding issues appear.
