### ISSUE TITLE
Server Error: "local variable 'session' referenced before assignment" when adding peer from list of available peers.

### ISSUE THREAD

**Issue by ggiesen** [respawner/peering-manager#208]
### Environment
* Python version:  3.7.5
* Peering Manager version:  1.1.1-dev (b6a156a1522dec00796f5f46a8b2d201a94d3457) -->

### Steps to Reproduce
1. Go to Internet Exchanges > <Internet Exchange Name > Available Peers
2. Select a peer to add
3. Click 'Add Selected'

### Expected Behavior
Be presented with the Internet Exchange Peering Session Import

### Observed Behavior
![peering_manager-add_available_peer](https://user-images.githubusercontent.com/5194146/75700714-87ac3280-5c80-11ea-94a5-ef1e845338e9.jpg)

### Notes
This seems to happen mostly (although not only) when I'm trying to add an IPv6 session for a peer with whom I already have an IPv4 session. I haven't been able to confirm this 100%, but it appears if I don't already have an IPv4 session, the 'Internet Exchange Peering Session Import' page prompts me to enter details for both sessions.

If I add the session manually (by going to Internet Exchanges > <Internet Exchange Name> > Peering Sessions, and then click the 'Add' button, I'm able to add the peer successfully.

**Comment by ggiesen** [comment]
I can confirm this is mostly fixed (for peers where I had an existing IPv4 session and was trying to add an IPv6 session). However I am still having an issue with some peers for whom I do not have any sessions. I was receiving the same error before, but now all I get is a blank page:

![peering_manager-add_available_peer_v2](https://user-images.githubusercontent.com/5194146/75730111-e8a42c80-5cb9-11ea-8302-9406832bffb2.jpg)

**Comment by respawner** [comment]
That's weird, it seems that I'm unable to reproduce the issue.

Can you give more details to reproduce the issue?
