### ISSUE TITLE
SUBJECT_PREFIX inserted into email subject

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#213]
### Environment
* Python version:  3.7.3
* Peering Manager version:  1.1.1-dev

### Steps to Reproduce

Populate `SUBJECT_PREFIX` in `configuration.py`:

```
EMAIL = {
    "SERVER": "smtp.example.com",
    "FROM_ADDRESS": "Peering <peering@example.com>",
    "SUBJECT_PREFIX": "Foo",
}
```

### Expected Behavior

When email is sent using Send E-mail tab in `http://peeringmanager/autonomous-systems/${ASN}/`, incoming subject line should be prefixed with `Foo`.

### Observed Behavior

Incoming email subject line is not prefixed with `Foo`.  It consists only of the subject line that is pre-populated with the email template name when the email template is selected.

**Comment by respawner** [comment]
From what I lookup in the [Django documentation](https://docs.djangoproject.com/fr/3.0/ref/settings/#std:setting-EMAIL_SUBJECT_PREFIX) is that this setting is supposed to work only when sending e-mails to admin and staff members.

If we still want to add a prefix to the e-mail subject, there are two ways to do it:

1. Add another option that will set the prefix for all e-mails
2. Add prefix right in the template name

Which one would suit you best?

**Comment by jlixfeld** [comment]
I think it’s probably more flexible to be able to add a prefix in the template name.  Possible to use a variable to make it super personal?

**Comment by respawner** [comment]
What kind of variable would you like to be exposed in this case?

**Comment by jlixfeld** [comment]
How about peer autonomous name, tags and ASN?

**Comment by respawner** [comment]
Fair enough, let's do this before 1.2.0.

**Comment by respawner** [comment]
Maybe it would be a good idea to separate e-mail and configuration template into two different models ; inheriting from the same one which would be almost identical the existing one. This would also be handy to pave the way to implement #240 as well.
