### ISSUE TITLE
Tags in templates are not a list, but a _TagManager

### ISSUE THREAD

**Issue by mngan** [respawner/peering-manager#214]
### Environment
* Python version:  3.6.9
* Peering Manager version:  master

### Steps to Reproduce
Include a test like this in a Jinja template
`{% if 'QFX5K' not in internet_exchange.router.tags %}...{% endif %}`

### Expected Behavior
This Jinja should compile properly

### Observed Behavior
If I try to test if a tag is in a tags field, I get an error saying tags is not iterable and is a class _TagManager

If I change this to be
`{% if  'QFX5K' not in internet_exchange.router.tags.names() %}...{% endif %}`
then is works as expected. So the tags are not being serialized into a list when passed into to Jinja. The docs indicate it should be a list of tags, but it is not.

**Comment by respawner** [comment]
This looks to be fixed for me since at least b213fe4. Can you confirm it too?

**Comment by mngan** [comment]
Yes, this addresses the problem, although if you go down the path of not calling to_dict(), you need to ensure that this still happens before handing off the model object to Jinja

**Comment by respawner** [comment]
Lets close this issue and make sure that it does not come back when we'll decide between keeping or removing `to_dict()`.

**Comment by mngan** [comment]
Hmmm... Actually it might not be fixed. I was looking at the wrong example. I still get an error. 

```
<class 'TypeError'>
argument of type '_TaggableManager' is not iterable
```

I think the problem is that to_dict tests for TaggableManager and not _TaggableManager.

**Comment by mngan** [comment]
I am not sure why some of the tags fields are being converted properly, but some are not. I have other references where I do the same `if tag in object.tags` and it works, but in this case `if tag in internet_exchange.router.tags` it fails.

**Comment by mngan** [comment]
I see the problem. It is because Router does not inherit TemplateModel. I think all the model classes have to do this since the code does recurse through nearly everything
