### ISSUE TITLE
Deployment via Docker

### ISSUE THREAD

**Issue by mxhob1** [respawner/peering-manager#222]
### Environment
* Python version: 3.7.3
* Peering Manager version: master

### Proposed Functionality
* To provide easy deployability of Peering-Manager via Docker containers
* For ease of integration it is a good idea to split the underlying Postgres DB to a separate container

### Use Case
Being able to implement Peering-Manager via Docker allows new users to rapidly deploy for testing and evaluation, as-well as allowing easy migrations across infrastructure. This has already been rolled in-house in multiple deployments and would serve as a good re-base of the functionality into the repo itself.

### External Dependencies
There would be no additional dependencies outside of Docker.

**Comment by respawner** [comment]
See https://github.com/peering-manager/docker
