### ISSUE TITLE
Search using tags

### ISSUE THREAD

**Issue by kzorba** [respawner/peering-manager#244]
### Tag search 

A very useful feature I think is the ability to search using tags, especially for Direct and the Internet Exchange peering sessions. I would like to have the ability to get a subset of the peering sessions via the API using tag matching.

### Use Case

A call like 

`
curl -H "Authorization: Token XXXXX" -H "Accept: application/json; indent=4" http://peering-manager.infra.msv/api/peering/direct-peering-sessions/?Tags=foo
`

should retrieve direct peering sessions matching `foo`. 
This kind of search should be available for all entities of peering manager, I guess this is the main purpose of having Tags. Composite search with tags should also be possible (using and/or etc).

**Comment by mngan** [comment]
I have something working that will do this in the UI and the API. It looks like there was code there to try to handle ?tag but it doesn't seem to work or isn't plumbed through correctly? What I have allows you to search with multiple tags to find matches that contain ANY of the supplied tags. I suspect that depending on how people are using tags, they may want an option to find matches that must contain ALL tags. I'll submit a  pull request once I finish up the feature.
