### ISSUE TITLE
Search for IX - Available Peers

### ISSUE THREAD

**Issue by rgarcia89** [respawner/peering-manager#25]
### Issue type
[x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.6.5
* Peering Manager version:  v0.99-dev

### Description

Add search function to Internet Exchange -> IX -> Available Peers.
Currently you are only able to list all peers that are connected to the IXs. However, within this you can only switch to the next page. It would be nice if it would be possible to search in this list for a specific AS.

**Comment by respawner** [comment]
Thanks for filling this issue.

This is something I am currently working in. The feature should land in master in the coming days :)

**Comment by rgarcia89** [comment]
Awesome looking forward to for the master release :+1:
