### ISSUE TITLE
Documentation inconsistencies for migrating to systemd and python venv

### ISSUE THREAD

**Issue by kzorba** [respawner/peering-manager#258]
### Proposed Changes
Hello,

I just upgraded to the head of peering-manager's repository and I did the change from supervisor to systemd, also putting peering-manager in a python3 venv. The documentation has some inconsistencies that could cause confusion to some people I think.

- Page [Setup | Peering Manager] mentions creating the user `peering-manager` and the venv
- Page [Setup | Web Server] mentions installing gunicorn but not in the venv. gunicorn.py has `command = '/usr/local/bin/gunicorn'` and user set to `www-data` instead of `peering-manager`. There are also a few typos in systemd section (service file should be `/etc/systemd/system/peering-manager.service` and `[[Unit]`). Finally in the service file the ExecStart should be fixed to contain `peering_manager.wsgi` (notice the underscore). With these changes the page will match [Setup | Migrate to systemd]
- Page [Setup | Migrate to systemd] should have the service file in `/etc/systemd/system/peering-manager.service`
- Page [Configuration | Configuring] contains reference to supervisor
- You should put somewhere changing the ownership of /opt/peering-manager to 'peering-manager'

Thanks

**Comment by respawner** [comment]
Should be fixed in b588d5b.
