### ISSUE TITLE
Enable guest access to view resources

### ISSUE THREAD

**Issue by lspgn** [respawner/peering-manager#268]
### Environment
* Peering Manager version:  1.2.0-dev d4bb98aa27c4

### Steps to Reproduce + Observed Behavior

When clicking on any link, if the user is not logged, they will be redirected to the login page.
Tried to disable this feature with:
`LOGIN_REQUIRED = False` in configuration.py without success.

### Expected Behavior

In v1.1.0, the default behavior allowed guest access to the resources. I believe this is preferrable for other teams to be able to easily access the resources without changing them.

**Comment by respawner** [comment]
It looks like it comes from the `permission_required = "peering.view_mymodel"` that has been introduced to be able to restrict some view to users. I wonder if it's possible to remove the permission requirement if `LOGIN_REQUIRED = False`.
