### ISSUE TITLE
Error when click on AS

### ISSUE THREAD

**Issue by jnikoletich** [respawner/peering-manager#27]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* Peering Manager version:  0.99-dev (latest commit)

### Description
So when clicking on Autonomous systems and the AS, I get the following error:

<class 'django.urls.exceptions.NoReverseMatch'>
Reverse for 'as_internet_exchanges' not found. 'as_internet_exchanges' is not a valid view function or pattern name.

**Comment by respawner** [comment]
Fixed in 16343a4.

Sorry for breaking the view.
