### ISSUE TITLE
bgp groups having no active sessions not exposed to bgp_groups list at template generation

### ISSUE THREAD

**Issue by mirackle-spb** [respawner/peering-manager#271]
### Environment
* Python version:  3.6.7-1~18.04
* Peering Manager version:  v1.2.0-dev

### Steps to Reproduce
Create bgp group. Create one session in it. Disable that session.

### Expected Behavior
group must be propaged to bgp_groups array is any session (active or not) in this group for this router exists 

### Observed Behavior
bgp group config will not be part of bgp_groups array at config generation. Session of this group cannot be disabled.
When i disable last session of group - it will not be disabled on router. It appear active because replace action is not executed.

**Comment by respawner** [comment]
Did you assign a router to the session?

**Comment by mirackle-spb** [comment]
Yes. This session was configured earler by peering-manager.

**Comment by respawner** [comment]
Weird indeed. Can you share the configuration template that you are using (if it's not one from the doc)?

**Comment by mirackle-spb** [comment]
Yes. I can share it. But is on 60% from doc. Give me your email. And i can send it to you.

**Comment by respawner** [comment]
I'm unable to reproduce this bug. I've committed a change to unit tests so they deal with disabled sessions as well (see ff4e4fd). It smells like a template issue. You can find my e-mail in the commit log (looking at the `Author` lines).

**Comment by mirackle-spb** [comment]
Sent to email. Looked again on template and looks like bgp_groups does not have group element. And than because of this session is not rendered in @inactive@ state. It just not render this group at all.

**Comment by mirackle-spb** [comment]
![Снимок экрана 2020-08-04 в 15 20 25](https://user-images.githubusercontent.com/8484332/89293129-0f4e0100-d666-11ea-84ad-c020856a95a1.png)
![Снимок экрана 2020-08-04 в 15 20 19](https://user-images.githubusercontent.com/8484332/89293134-107f2e00-d666-11ea-9133-583bd23d1b96.png)
There is screenshots of group and only one peering session in it.

**Comment by mirackle-spb** [comment]
Oh. My bad. Sorry. The eye is covered with dust.
