### ISSUE TITLE
UI improvement for NAPALM related actions

### ISSUE THREAD

**Issue by jnikoletich** [respawner/peering-manager#3]
I see that there is references to napalm in the code. Starting with the routerping feature. When I click on the ping button nothing seems to happen. Is this live yet?

btw... love the project

**Comment by respawner** [comment]
This is indeed live but it lacks some UI feedback.
If the connection to the router is pretty quick you'll see it working. But if the connection is slow or if it is unable to connect the timeout (which is quite long) will make the user wondering if it works.

I need to add some kind of loading spinner so the user can see that it is actually doing something.
