### ISSUE TITLE
Squash database migrations before releasing v1.0

### ISSUE THREAD

**Issue by respawner** [respawner/peering-manager#31]
Every time we are modifying the database schema (by modifying models) a migration containing a piece of code is generated. Due to the high development of Peering Manager there are multiple files generated over the time.

We can compress all of these migrations into one if the database remains consistent while applying them. We could probably do this for each stable release (once will have one).

**Comment by tobzsc** [comment]
Any plan when 1.0 will be released? Currently, we see heavy development and no stable database scheme.

**Comment by respawner** [comment]
When it's ready 😄 

To be honest I'd like to implement some basic features and get a stable database scheme (which depends on previously mentioned features) before freezing for the 1.0.0.

If some people want to help, bug triage and bug fixes is the best way to do so. But I don't force anyone since it takes time 😄

**Comment by tobzsc** [comment]
I completely understand that. We are about to implement peering-manager for our infrastructure but aiminig for a stable version. I expect there will be no way to go from the recent dev to a coming 1.0.0? That's why we are aiming a start with a stable release :)

**Comment by respawner** [comment]
You should be able to go from dev to stable without any troubles. Squashing database migrations will just here to optimize the process to apply them. This process should not break any existing databases. Talking about this makes me think that it might be a good idea to provide a way to dump the database and restore it before 1.0.0.
