### ISSUE TITLE
Using NetBox for router list

### ISSUE THREAD

**Issue by respawner** [respawner/peering-manager#32]
### Issue type
[x] Feature request
[ ] Bug report
[ ] Documentation

### Environment
* Python version: 3.7
* Peering Manager version:  master

### Description
Using multiple tools for managing a network and its automation can lead to data duplication. This is never good in most cases because at one point one of the tools will not be updated and the data duplication will start causing some misbehavior or misunderstanding.

[NetBox](https://github.com/digitalocean/netbox/) is a DCIM/IPAM tool in which people can document their infrastructures and track the devices they are managing.

It will be a good idea and feature to be able for Peering Manager users to use the devices they have already created inside NetBox instead of creating `Router` objects.

We can consider that if a user is using NetBox as source for routers details, there will be no points for him to create routers locally. The UI and the permissions related to it must be reviewed accordingly.

**Comment by amtypaldos** [comment]
We use netbox here so would definitely test if you need help on that.  My python is OK so not sure how much development help I can be, but would love to try.

**Comment by respawner** [comment]
Implementation started with a4c415e. We do need more work on this (frontend and backend).

1. Using management details found in NetBox
2. Using platform (with NAPALM support) found in NetBox
3. Keep details in sync

Any other stuff?

**Comment by 2bithacker** [comment]
> Implementation started with [a4c415e](https://github.com/respawner/peering-manager/commit/a4c415e9f53918b9d917435a8caa1f09bc780a8b). We do need more work on this (frontend and backend).

I was just looking at this as part of some work to communicate with devices via NetBox's NAPALM API call (instead of talking directly via NAPALM) and it looks like this isn't handling pagination in the API response, so if there are more than 50 devices you'll only get a subset.

It'd probably be better to pass the device roles as filter parameters to the NetBox API as well, rather than grabbing all the devices and filtering client-side.

Would you be opposed to pulling in [pynetbox](https://github.com/digitalocean/pynetbox)? It handles the pagination issues.

**Comment by respawner** [comment]
> Would you be opposed to pulling in [pynetbox](https://github.com/digitalocean/pynetbox)? It handles the pagination issues.

It sounds legit. So I'm not against adding `pynetbox` to requirements.

**Comment by respawner** [comment]
@2bithacker are you happy with the way Peering Manager is interacting now or do you have more improvements in mind that we could include in this issue?

**Comment by 2bithacker** [comment]
I'm happy with how it's working at the moment.

**Comment by respawner** [comment]
@2bithacker thanks for the feedback.

Closing, further improvements can still be documented in other issues.
