### ISSUE TITLE
 Available Peers not showing all peers

### ISSUE THREAD

**Issue by FredNeuberger** [respawner/peering-manager#33]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.3-1
* Peering Manager version:  peering-manager (v0.99-dev)
Debian 9.1.0

### Description
We currently have 10 peering sessions with 3 different peers in the INEX LAN2.
If I click on "Available Peers" from within the IX view of INEX LAN2, I do see only 5 available peering sessions from 4 different peers.

![inex_lan2_availpeers](https://user-images.githubusercontent.com/33221829/43520109-17f81eba-9592-11e8-9d27-6ef155b13a18.PNG)

Not sure where "Regional Broadband Ireland" is coming from, since according to PDB they are only connected to LAN1 ... after checking the local DB, it looks like there are two entries that might explain this:
![as47942_local_db_entries](https://user-images.githubusercontent.com/33221829/43520392-09fa0f52-9593-11e8-837a-8e80d8237995.PNG)

Looks like other IX show similar behavior in our setup.

Logs didn't show any related. Please let me know if you need any additonal information.

**Comment by respawner** [comment]
Did you try rebuilding the local cache from scratch or rebuilding the peer records indexes?
![pm-cache-controls](https://user-images.githubusercontent.com/736209/43522482-cd7466e8-9599-11e8-8421-2e66b037acb2.png)

**Comment by respawner** [comment]
Did you had the chance to try rebuilding the cache and peer records indexes?

**Comment by respawner** [comment]
Closed due to lack of activity.
