### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by jnikoletich** [respawner/peering-manager#4]
Hi,

I am really loving this project and we are activelly using it. I was wondering if I could sponsor some development time or just some beer money to show appreciation. 

I think the features I would like seen are:

1) Peering session status with received and sent prefix numbers. (via NAPALM) 
2) IRR prefix filter generation for peers. Like bgpq3/etc (via NAPALM)
3) Peering request in the GUI. So we can just have a template and when searching an AS we hit a "Request to peer". It would send them an email template with details/etc.

Let me know if I can get some beer money your way.

**Comment by respawner** [comment]
Hello,

Thanks for your positive feedback. I really appreciate it. 👍 

I'd never believe someone would use this so quickly at such an early stage in the development. The code is far from perfect and tastes a bit "alpha" to me. But I'm glad it actually works for someone.

About the feature you would like to have, they are already on my TODO list. So I'd like to make them come true as soon as possible. But to perform some tests while writing these features I need to make some kind of lab environment with virtual routers to simulate some kind of Internet exchange points. Having a proper lab setup would greatly improve the development speed and tests.

About sponsoring development time or beer money, this is the first time someone asks me this question. I'm not against this as far as the code produced remains open source/free and available to anybody.

If you want to discuss this further, you can take a look at [my Github profile](https://github.com/respawner) and you should find your way to my email address from there.

**Comment by jnikoletich** [comment]
Thanks. I have sent you an email. Let me know if you have received it.

**Comment by FredNeuberger** [comment]
Hi,

In regards to the sponsorship stuff, I was also thinking about getting in contact with you for some time now. Somehow I wasn't able to find any contact information, maybe I need glasses or something.
Would it be okay to contact you on that one platform that is being mentioned there?

Cheers

**Comment by jnikoletich** [comment]
@FredNeuberger Glad to know other are interested. What features are you looking to have added as well?

**Comment by FredNeuberger** [comment]
@jnikoletich I'm not totally sure yet as I don't have the feeling that I have fully explored how peering-manager is working. I probably need to invest some more time into playing around. I haven't even started yet with the Apache part yet, still running on that testing mode.

What I can think of right now is:
- Discovery of configured peerings, because I believe 90% of the potential users already have peerings in place. Opened feature request #8 for this

- Private peerings might be interesting too. Not sure that is a feature that a lot of people need. Just came to my mind when thinking about having a one stop shop for peering documentation and configuration.


Not sure how @respawner would want us to handle all the request that we might have.
Maybe open an issue right away explaining things in detail or maybe create a list and then create issues for stuff that we really would want to see (prioritised). I wouldn't want to flood the project with crazy request :-)

**Comment by FredNeuberger** [comment]
Not sure if I just missed it in the GUI, but it would be totally cool to see missing session.
We normally peer with other networks at every possible IXP in every possible combination.
If both parties have two routers at the IXP, that would be 8 sessions in total for us.
You might forget a session or the other party added a new router to an existing IXP or even connected to a new IXP.

Another thing related to that, would be the detection of non existing neighbors as in:
A session is configured, it is down and there is no corresponding entry for the other party in PDB
Usually is the case when a network is leaving an IXP.

I'd say both features would be "nice to have" and there is probably a lot more important stuff right now.

In regards to the contact details (few post above), I've found it and send something :-)

**Comment by respawner** [comment]
Hello,

I have enabled the Wiki feature for this project and created a [whishlist page](https://github.com/respawner/peering-manager/wiki/Whishlist) where you can put all your ideas on.

In this way we will have a list of features that you would like to have, classify them, prioritize them, etc.

Feel free to edit this page.

**Comment by FredNeuberger** [comment]
Not sure if there is a hidden button to edit the wiki page, but I don't see a way to edit that page.
Is it maybe some privilege thing?

**Comment by respawner** [comment]
You should be able to edit the wiki page now.

**Comment by FredNeuberger** [comment]
Very nice, thanks
Added some stuff.

**Comment by respawner** [comment]
If you want to donate some money and have a PayPal account you can check [this link](https://paypal.me/GuillaumeMazoyer).

Any money will go straight to my PayPal account. Depending on the amount of money we can talk about sponsorship, etc… I'm new to this kind of stuff.

I'll close this issue for now.
