### ISSUE TITLE
Expose an API

### ISSUE THREAD

**Issue by respawner** [respawner/peering-manager#41]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.7
* Peering Manager version: master

### Description

Expose an API so the user can interact with Peering Manager using other pieces of software.

We should take a look at [Django REST Framework](http://www.django-rest-framework.org/).

**Comment by omershtivi** [comment]
I think that we shall implement the api as:
api/v<version of api>/methods
it works better that if we want to change some api behaviour we can just increase the version and we won't break the API for other that already have code working with a previous release of the system.
Example:
api/v1/
Next time we want to change
api/v2/

**Comment by respawner** [comment]
A token based authentication mechanism should also be introduced to avoid using username/password, keeping people from the temptation of storing clear text password in some configuration files (for example).
