### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by omershtivi** [respawner/peering-manager#44]
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* Peering Manager version:  

### Description
Allow users to see the system settings, and edit them.

**Comment by respawner** [comment]
I don't want settings required to be exposed on a view.

Settings (configuration) are critical for Peering Manager and might need to restart the python workers if changed. So we will only support settings to be edited in the proper file.
