### ISSUE TITLE
No support for IOS

### ISSUE THREAD

**Issue by rinsekloek** [respawner/peering-manager#46]
### Issue type
[ ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* Peering Manager version:  

### Description
I discovered there is no support for IOS in Peering Manager. So I created a fork https://github.com/rinsekloek/peering-manager and made some support for IOS.

**Comment by respawner** [comment]
This issue should be fixed using NAPALM 2.3.2. In this version NAPALM introduced the `get_bgp_neighbors_detail` for IOS which is a requirement for getting peering sessions details in Peering Manager. Whitelisting IOS as a platform capable of giving BGP neighbors details should be enough.
