### ISSUE TITLE
UNIQUE constraint failed: peering_internetexchange.slug

### ISSUE THREAD

**Issue by FredNeuberger** [respawner/peering-manager#5]
Hi there,

First of all, let me say that the idea of this project is great.

Did you try to talk to the PeeringDB guys to spread the word about this or maybe even get some support from them?

Anyways, I did a clean install in an Ubuntu 16.04 LXC setup.
Besides logging in, I just went to "Internet Exchanges" and clicked on "Import from PeeringDB" and got this error:

There was a problem with your request. This error has been logged and administrative staff have been notified. Please return to the home page and try again.

If you are responsible for this installation, please consider filing a bug report. Additional information is provided below:

<class 'django.db.utils.IntegrityError'>
UNIQUE constraint failed: peering_internetexchange.slug

/opt/peering-manager/logs/peering-manager.log looks like this:
2018-01-24 23:58:57 | DEBUG | calling api: https://peeringdb.com/api/netixlan | {'asn': <myasnhere>, 'depth': 1}

Great job so far.

Cheers

**Comment by jnikoletich** [comment]
@FredNeuberger Did you try syncing the peeringdb database first via the command line and install instructions?

**Comment by FredNeuberger** [comment]
@jnikoletich Thanks for the quick reply.
Are you referring to "Caching in the Local Database"

No, I didn't do that this time. I did though in my first install try but got some weird results then trying to import the IXPs from PDB. I probably messed things up there at some other point.

With the re-install it seemed to me, that you don't have to have a local cache of PDB, as it gathers at least the IXP infos for our ASN on the fly.

**Comment by FredNeuberger** [comment]
Update: Three Internet Exchanges were added, looks like one of the other ones caused the issue.

**Comment by FredNeuberger** [comment]
Okay, I've created a fresh LXC Ubuntu 16.04 container and re-installed.
After clicking the "Sync from PeeringDB" button in "Internet Exchange", I've manually renamed "name" and "slug" so that both of them are unique. That actually did the trick, as all entries were imported.

Btw, is there an easy way to reset the whole P-M setup to start from scratch?

**Comment by respawner** [comment]
There is indeed an issue with the "Import from PeeringDB" feature for now.

Slugs are supposed to be unique for each IX. You can imagine them like database IDs (even if they are not). So It can happens that when trying to import IXs from PeeringDB several **slug** fields result in the same value.

For now there is no check when the forms are submitted to see if all slugs have different values. We must make sure that these fields are indeed unique before accepting the submitted form (which is in fact several forms). If two or more slugs are unique the form must return an error and notify the user about it in a human-understandable way.

btw, if you want to reset the whole peering-manager from scratch, just delete the **db.sqlite3** file.
