### ISSUE TITLE
Better Deploy exception detection throwing and/or logging

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#52]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.3 
* Peering Manager version: v0.99-dev 

### Description

Deploy should be able to pull errors from napalm, like discern if the config is locked (I think this is returned by napalm?) or if the device is unreachable (I think this too is returned by napalm?) or if an error is thrown during the deploy.

I just tried to deploy a config that I knew would introduce changes to the config, but upon completion, it reported there were no differences in the config. After reviewing the logs, I saw there was in fact an issue that PM didn't log or throw an exception for:

```
2018-10-28 12:04:14 | DEBUG | unable to merge configuration on bfr01.1250ReneLevesqueBl01.YUL reason "Invalid input entered:

    maximum-prefix 0 95 restart 60
                   ^
% Invalid input detected at '^' marker.
"
2018-10-28 12:04:14 | DEBUG | closing connection with bfr01.1250ReneLevesqueBl01.YUL
```

**Comment by respawner** [comment]
Indeed that's quite an interesting topic that you've just raised. Actually this is a topic I've been working on when releasing the code to apply the configuration using NAPALM.

NAPALM does raise exceptions when trying to merge a configuration into another. What it does is that if there are any kind of issue we expect NAPALM to raise a `MergeConfigException`. We then have to inspect the message of the said exception to know what actually happened.

The code handling this in Peering Manager is [here](https://github.com/respawner/peering-manager/blob/519db273de94c4a5fb3c7fe77d49a147e2e8daf3/peering/models.py#L922). Changing the `set_napalm_configuration` return value could help knowing if an actual error occurred or if it was changed that no changes had to be done. Yeah the current code returns a value interpreted as a boolean equaled to `false` if no changes have been applied (meaning even in case of an error).

Changing the return value of the function using maybe a tuple could be an idea like: `return (success, message)`. `success` would be a boolean value telling if the operation was successful. `message` could be used as a variable to carry, either the changes to be applied or the actual error message.
