### ISSUE TITLE
Show all available sessions

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#57]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:   3.5.3
* Peering Manager version:   0.99-dev

### Description

There doesn't seem to be a way to see/search available sessions for all common IXs at once.  I have to go into an IX first, then select the Available Sessions tab and then search for the AS I'm interested in.

Does/can #24 address this, or should that be a different feature request?

**Comment by respawner** [comment]
This will be addressed with #24 indeed.
