### ISSUE TITLE
Server Error when adding new peer

### ISSUE THREAD

**Issue by randy-404** [respawner/peering-manager#61]
### Issue type
[ ] Feature request 
[x ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* Peering Manager version:  Updated NOV 08 2018

### Description
When attempting to add a new peer(s), the following error message appears...

---------

```
Server Error 
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:
<class 'peeringdb.models.NetworkIXLAN.DoesNotExist'>
NetworkIXLAN matching query does not exist.
```

----------

Steps to reproduce are simple...
1. Select an IX
2. Select any peer(s)
3. Click the "+ Add Selected" button
4. Error appears

- Tried different IX's, problem still exists
- Updated to the latest Master, problem still exists. 
- Restarted Peering Manager, problem still exists
- Tried with different browsers, problem still exists

Please let me know if you have any additional questions or require any further information.

Thanks in advance for your assistance.

-R

**Comment by respawner** [comment]
Did you try rebuilding the PeeringDB cache using the command line interface `python manage.py peeringdb_sync`?

In theory, if the peer appears in the list (since data are gathered from `peeringdb.Network` and `peeringdb.NetworkIXLAN` models, it means that the object should exists. I'll take a look at the function that takes care of looking up the object though.

**Comment by randy-404** [comment]
Yes, I ran the command `python3 manage.py peeringdb_sync` before opening the bug report. I ran it again today, just to be sure. The problem still exists.

**Comment by respawner** [comment]
And what if you try to re-index peer records, using the feature in the cache management view?
<img width="698" alt="capture d ecran 2018-11-09 a 21 36 26" src="https://user-images.githubusercontent.com/736209/48286989-a40ed500-e467-11e8-94ec-06eca0a666a3.png">

**Comment by randy-404** [comment]
Looks like the same (or very similar) to issue #56

**Comment by randy-404** [comment]
Updated to the latest code. Attempted to run the provided command, received the following output...

```
root@ops:/opt/peering-manager# python manage.py index_peer_records
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

**Comment by jlixfeld** [comment]
Maybe you have to call it with python3 instead of python

**Comment by randy-404** [comment]
y'all were correct... I had to use python3 in order to get the command to run. Command was run successfully. Problem still remains. When adding a peer, I get the same message as the original post.

```
Server Error 
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:
<class 'peeringdb.models.NetworkIXLAN.DoesNotExist'>
NetworkIXLAN matching query does not exist.
```

**Comment by respawner** [comment]
Is the issue occurring for only one specific peer or for several? If it is for a specific peer can you give me the details for it?

**Comment by randy-404** [comment]
Problem occurs with any peer or number of peers, and I've tested on several different exchanges.

**Comment by respawner** [comment]
That's weird, I'm still unable to reproduce the issue. In the `/admin/peeringdb/peerrecord/` how many records do you have?

**Comment by randy-404** [comment]
There are 25424 peer records

**Comment by respawner** [comment]
Looks like it's OK. So the issue is getting weirder. Would you mind giving us the peer details so I can check with my test installation?

**Comment by randy-404** [comment]
I wish I could be more specific and it was just a specific peer or exchange, but it's not. We're talking about literally any peer that isn't already added on any of the configured exchanges in our Peering Manager installation.

**Comment by respawner** [comment]
Can you turn on the debug setting `DEBUG = True` in your configuration file so we can have more details about the issue (and the full stacktrace)?

**Comment by respawner** [comment]
> Just to confirm, you're referring to the configuration.py file, yes?

Yes, indeed.

**Comment by randy-404** [comment]
Added the DEBUG = true line in the configuration.py file, restarted peering-manager, now getting either Proxy Error or Service Unavailable error when trying to access peering manager. Tried restarting the server with same results.

**Comment by jlixfeld** [comment]
Make sure the log files are owned (user and group) by the same user that runs the web server or else gunicorn will not be able to start.

**Comment by randy-404** [comment]
Acknowledged. Directory is owned by the correct User. I can confirm gunicorn is started, but peering manager is still not working. Same issue.

**Comment by respawner** [comment]
I strongly recommend using the Django test server while using the debug mode. This will avoid other software interfering with the debug. You can start the test server using `python3 manage.py runserver`.

**Comment by jlixfeld** [comment]
So now I'm seeing this issue too when adding a peer.  Specially, adding AS32590 to SIX Seattle: MTU 1500.

I first deleted the caches as a troubleshooting step:

```
root@peeringmanager:/opt/peering-manager# python3 manage.py peeringdb_sync
root@peeringmanager:/opt/peering-manager# python3 manage.py peeringdb_sync_as
root@peeringmanager:/opt/peering-manager# python3 manage.py index_peer_records
```

There are 25461 peering records in `/admin/peeringdb/peerrecord/`

Incidentally, it looks like there are 255 pages of output in that view.  255 is a really interesting number :)

<img width="421" alt="screen shot 2018-11-17 at 1 55 44 pm" src="https://user-images.githubusercontent.com/17339017/48664692-98776b80-ea70-11e8-88e2-5475b94edf34.png">

Here's the dump from DEBUG = 'true'

(do you need everything on that page, or just the traceback?)

(@randy-404, wrap true in quotes as above and see if you can start it)

```
Environment:


Request Method: POST
Request URL: http://peeringmanager.beanfield.com/internet-exchange-peering-sessions/add_from_peeringdb/?network__irr_as_set=&q=valve&network__asn=&network__info_prefixes4=&network__name=&network__info_prefixes6=

Django Version: 2.1.3
Python Version: 3.5.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_filters',
 'django_tables2',
 'peering',
 'peeringdb',
 'utils']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'utils.middleware.ExceptionCatchingMiddleware',
 'utils.middleware.RequireLoginMiddleware']



Traceback:

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/mixins.py" in dispatch
  85.         return super().dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/opt/peering-manager/utils/views.py" in post
  182.                     self.process_dependency_object(dependency))

File "/opt/peering-manager/peering/views.py" in process_dependency_object
  758.             dependency, 6)

File "/opt/peering-manager/peering/models.py" in get_from_peeringdb_peer_record
  738.             ixlan = NetworkIXLAN.objects.get(id=ix.peeringdb_id)

File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py" in get
  399.                 self.model._meta.object_name

Exception Type: DoesNotExist at /internet-exchange-peering-sessions/add_from_peeringdb/
Exception Value: NetworkIXLAN matching query does not exist.
```

**Comment by respawner** [comment]
Weird that's so weird.

Actually if the `NetworkIXLAN` is deleted, the `PeerRecord` must be deleted as well. That's the goal of `on_delete` statements in [here](https://github.com/respawner/peering-manager/blob/76b3481bffe910eaca70ee5bdc26ce01f1b04275/peeringdb/models.py#L87).

Maybe I should try to make a script testing the "integrity" of the database.

**Comment by respawner** [comment]
@jlixfeld I manage to reproduce the issue thanks to your details.

**Comment by jlixfeld** [comment]
Great!  Any thoughts on a workaround until a code fix?

**Comment by respawner** [comment]
The only workaround is to add the peering sessions manually while waiting for the fix. I'm still investigating on the issue.

**Comment by jlixfeld** [comment]
Oh you mean add them to the router manually?

**Comment by respawner** [comment]
No I mean that you can create the peering session manually inside peering manager from the peering session list view for the IX. You get the same fields than when you are importing the session except they will not be pre-filled with the details.

**Comment by respawner** [comment]
Could you upgrade to 3e05821 and check if an alert is displayed on IXs having the issue?

**Comment by jlixfeld** [comment]
Looks good!

So can you help me understand the root cause of this issue, for my own understanding?  As far as I understand, PeeringDB has an ID for the each LAN/network and that ID is saved into Peering Manager when the cache is created.  For some reason the PeeringDB ID for LAN/network changed but it was not reflected in Peering Manager.  Are all peers pulled from PeeringDB with it's associated PeeringDB ID for the LAN/network, and that object in Peering Manager was also linked to a non-existent PeeringDB ID?

**Comment by randy-404** [comment]
Not sure if you were asking me to update, but I just updated to the latest version and the issue still persists. Do I need to Re-index peers, clear cache and update cache?

**Comment by respawner** [comment]
> Looks good!
> 
> So can you help me understand the root cause of this issue, for my own understanding? As far as I understand, PeeringDB has an ID for the each LAN/network and that ID is saved into Peering Manager when the cache is created. For some reason the PeeringDB ID for LAN/network changed but it was not reflected in Peering Manager. Are all peers pulled from PeeringDB with it's associated PeeringDB ID for the LAN/network, and that object in Peering Manager was also linked to a non-existent PeeringDB ID?

@jlixfeld This is almost what you described. When you import IX from PeeringDB, the ID for each one of them is locally saved. This ID is the one from the PeeringDB `NetworkIXLAN` object that represents your connection to an IX (IP addresses, ASN, etc…). This `NetworkIXLAN` is then used to get the available peers list. When you select peer sessions to add them, Peering Manager loops over every IXs that you add so find which is the one the peer sessions that you are trying to add should belong to. If by any reasons one of this IX still have an invalid PeeringDB ID, an error occurs and the exception that you experienced is raised.

I'm not sure if I'm clear enough but it's a bit complicated to describe how this piece of code works.



> Not sure if you were asking me to update, but I just updated to the latest version and the issue still persists. Do I need to Re-index peers, clear cache and update cache?

@randy-404 Yeah I wanted to have your feedback too. You do not need to re-index peers and clear/update caches. I just want you to check if you have an alert for an IX (no matter which one) in your Peering Manager instance. If you have an alert (red ribbon on top of the IX details view) this means that there are a mismatch between the ID of the PeeringDB object that we store and the real one.

Anyway, there should be a way to fix this automatically by making the proper API call to PeeringDB. I'm working on this right now to fix the issue automatically or if the issue appears to be unfixable by some code then warn the user about it.

**Comment by randy-404** [comment]
I now see the message you are referring to, but it shows on only one of our eleven configured IX's (AMS-IX NY). However, the issue is still happening not just for that one IX, but all of them.

**Comment by respawner** [comment]
> I now see the message you are referring to, but it shows on only one of our eleven configured IX's (AMS-IX NY). However, the issue is still happening not just for that one IX, but all of them.

Yeah that normal. It is because of a `for` loop that is trying to lookup what IX the sessions have to belong to after being imported. If you delete the IX causing the issue, or fix the PeeringDB ID or the ID, it should work.

**Comment by jlixfeld** [comment]
After that I seemed to have 2 SIX entries :(  Not sure what was going on there.

**Comment by respawner** [comment]
That's unfortunate but it's a normal behavior (giving the current code state). Peering Manager does not enforce IX to be unique (maybe it should, at least for the `peeringdb_id` field). I'd recommend removing the second IX and continue manually grab the right ID from PeeringDB for the first IX. This can be done by clicking on one of the links in the alert message.

Starting from b76d737, Peering Manager should be able to fix PeeringDB ID for IX automatically if that's possible (thanks to the IP addresses set for the IX).

**Comment by respawner** [comment]
Thanks for the feedback. I'm closing the issue for now. You can re-open one if you need.
