### ISSUE TITLE
Encrypt session passwords once

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#62]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:   3.5.3
* Peering Manager version:   0.99-dev

### Description

It makes sense to be able to retrieve the unencrypted passwords from PM incase they are required.  However, any time a configuration is deployed, the password is re-hashed which creates a config diff.  If you get regular email reports of config diffs, that can get noisy :)

I think the fix is to have PM hash the password for each supported device type and store the clear text password as well as the device-specific hashed password(s). Whenever a configuration is deployed, it inserted the pre-hashed password.

**Comment by respawner** [comment]
I agree with the feature. For now I'm doing things on my end with some quick and dirty perl script using [this](https://metacpan.org/pod/distribution/Crypt-Juniper/lib/Crypt/Juniper.pm). I guess that it should not be that hard to rewrite this in Python.

The idea is (in my opinion) to propose the choice of encryption to the user (Juniper, Cisco, whatever or none).

**Comment by jlixfeld** [comment]
Can we add a hook for IOS-XR platform type which does not use `7 ${encrypted string}`?

IOS-XR uses the following:

If entered clear, config is: `password clear mysecurepassword`

If entered encrypted, configs is: `password encrypted 045612150A22595C0C090404011C03162E`

**Comment by respawner** [comment]
Oh Cisco it's a pain trying to automate things with you 😄 
Can you open a new issue (bug report) to track this?
