### ISSUE TITLE
"Return to search" breadcrumb

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#65]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:   3.5.3
* Peering Manager version:   0.99-dev

### Description

A breadcrumb to return to search results would be helpful for these scenarios:

1.  Perform a search, edit one of the results, click cancel or update, brings you to "Details", you can't get back to the search results without using browser back button.

2. Perform a search, click "Details".  You can't get back to the search results without using browser back button.

**Comment by FredNeuberger** [comment]
Ran into this when I created Routing Policies. Would be nice if you could jump back to the list after you created or edited one.

**Comment by respawner** [comment]
> Ran into this when I created Routing Policies. Would be nice if you could jump back to the list after you created or edited one.
> 
> EDIT: There are probably some more cases where this could be useful some way.

This will be partially fixed when PR #82 will be merged into `master`.

I'm still trying to figure out how to implement the "Return to search" feature though.

**Comment by respawner** [comment]
Implementing a search history with the last 10 searches for instance, could be a way to solve this.

We could then display a button/link in the header like "Last search" as a shortcut and have a bit more searches available in a sub-menu of the user menu.

Just an idea, nothing's decided yet. What do you guys think?

**Comment by jnikoletich** [comment]
Honestly, I don't think there is a need to keep a history. Just a simple return to search should suffice. It is something I wouldn't use but I can see use cases for it. I am happy just using the back button.
