### ISSUE TITLE
Decide of a database backend

### ISSUE THREAD

**Issue by respawner** [respawner/peering-manager#74]
### Proposed Changes

Decide of a database backend to be used and officially supported (SQLite, PostgreSQL, MySQL/MariaDB).

### Justification

The current code is not specific to any sort of database as long as Django supports it. For our use case we will probably need to decide which database backend we should use and support.

  1. This will give an official way to setup Peering Manager for the user
  2. This might help decide what can be done in the database backend and what has to be done through our code
  3. It will definitely drive this project towards a production ready piece of code

For now I would be in favor of dropping SQLite to settle with PostgreSQL mostly due to the nature of this project, handling IP addresses and stuff. PostgreSQL has the advantage of having a [type of field to store IP addresses](https://www.postgresql.org/docs/9.4/datatype-net-types.html). There is also a [field for JSON data](https://www.postgresql.org/docs/10/datatype-json.html) that might be of help for later use.

If anyone has an opinion about this, I would be glad to read it.

**Comment by tobzsc** [comment]
PostgreSQL is the right choice in my eyes. For development SQLite was sufficient but as the project and use cases grow this is not enough anymore. +1 for Postgres!

**Comment by respawner** [comment]
We should also propose a script to migrate data from SQLite to the new database backend to avoid any loss of data.
