### ISSUE TITLE
Allow InternetExchangePeeringSession to be identified as routes server session

### ISSUE THREAD

**Issue by rgarcia89** [respawner/peering-manager#76]
### Environment
* Python version:  
* Peering Manager version:  

### Proposed Functionality
To be able to create a generic template without having to touch a lot of sessions, I would like to check if the type of the session = Route Server. In that case, we would like to use the information that are available in the Peering DB field _Also Known As_.

### Use Case
```
{%- if session.is_route_server and group.ip_version == 6 %}
    address-family ipv6 unicast
    route-policy ng6-in-{{ session.alsoKnownAS }} in
    route-policy ng6-out-{{ session.alsoKnownAS }} out
{%- elif session.is_route_server and group.ip_version == 4 %}
    address-family ipv4 unicast
    route-policy ng4-in-{{ session.alsoKnownAS }} in
    route-policy ng4-out-{{ session.alsoKnownAS }} out
{%- elif not session.is_route_server and group.ip_version == 6 %}
    address-family ipv6 unicast
    route-policy ng6-in-PEERING in
    route-policy ng6-out-PEERING out
{%- elif not session.is_route_server and group.ip_version == 4 %}
    address-family ipv4 unicast
    route-policy ng4-in-PEERING in
    route-policy ng4-out-PEERING out
{%- endif %}

```

**Comment by tobzsc** [comment]
This is a great request! We are also looking for this!

**Comment by tobzsc** [comment]
@respawner great that you have realised that so fast. I think you did a mistake for the db migations...

is_router_server -> is_route_server

That should be syntactical correct.

**Comment by respawner** [comment]
> is_router_server -> is_route_server

Thanks for the feedback, I didn't see the typo and auto-completion working like a charm has propagated it everywhere :)

**Comment by rgarcia89** [comment]
Awesome thank you @respawner 
Still need to update to the db using version. 
However, I am very looking forward to it :+1:
