### ISSUE TITLE
Handling IX with redundant peering ports

### ISSUE THREAD

**Issue by tobzsc** [respawner/peering-manager#78]
### Environment
* Python version:  3.6.x
* Peering Manager version:  master

### Proposed Functionality
It may be that you have redundant ports on the same IX. In that case it is hard to differentiate for which port you are doing changes. It is working without any issues but in the configuration process of sessions it is hard to see for which peering port you are doing changes.

### Use Case
Management of redundant ports at same exchange.

**Comment by respawner** [comment]
What are you calling redundant ports? Are these ports using different IP addresses to connect to the IX? If that's the case I would suggest declaring two different IXs.

However I might not understand your case so could please give us more details about it?

**Comment by tobzsc** [comment]
I am talking about ports with different IPs at the same IX. Give me some time to prepare some information.

**Comment by FredNeuberger** [comment]
If you are talking about having two routers at the same IXP, that should be covered already. You just have to give the slugs a unique name (not sure about the IXP name though) during the import from PDB.

**Comment by respawner** [comment]
> If you are talking about having two routers at the same IXP, that should be covered already. You just have to give the slugs a unique name (not sure about the IXP name though) during the import from PDB.

Indeed. IXP name do not need to be uniques (only slugs).

**Comment by respawner** [comment]
Closing because this feature can already be used.
