### ISSUE TITLE
Question:  What is the main peering key for a PeeringDB entry

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#80]
Hello,

An IX we participate at is changing their LAN prefix next week.  They are working with PeeringDB to push an update so all peer entries for that IX are updated with the new subnet.

My question is what will Peering Manager do when it polls PeeringDB after the subnet change push has been done for that IX?  Will it simply change their IP address of the existing peer, or will it treat the peer as a new peer because of the new IP address, and we'll need to import all the existing peers again?

**Comment by respawner** [comment]
It will basically do nothing except detecting the new IX prefixes so you can import peers from your router configuration. Actually no logic has been implemented to handle such case and I don't think it worth the shot (for now at least). That said, we could use a feature to detect sessions not using the correct IP for some peers at some IX, we'd have to trust PeeringDB blindly though.

**Comment by jlixfeld** [comment]
That's pretty much what I thought. That's no big deal. It's not like you get IXPs changing their LAN prefixes every day, so the bit of manual work it takes to re-import and delete is really quite trivial in the grand scheme of things.  In fact, with the DB backend now, it's probably trivial to script the deletes :)
