### ISSUE TITLE
log to syslog

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#87]
### Environment
* Python version:  3.5.3
* Peering Manager version:  master

### Proposed Functionality

- Option for any logs generated by peering manager applications (peering-manager.log, napalm.log, peeringdb.log, netbox.log, etc) to be written to syslog

### Use Case

- If someone is running a central syslog parser, it will can catch errors thrown by peering-manager (ie: napalm deploy errors) syslog and send email alerts from the central syslog parser.

**Comment by respawner** [comment]
Django provides everything we need to send logs to syslog or anything else. We'll just have to let the user be able to change the `LOGGING` config option.
