### ISSUE TITLE
Pager doesn't work in Safari

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#89]
### Environment
* Python version:  3.5.3
* Peering Manager version:  master
* OS: MacOS 10.14.3
* Browser: Safari 12.0.3

### Steps to Reproduce

- Visit page with pagination using Safari browser on MacOS.

### Expected Behavior

- Selecting the number of results refreshes the page and displays the desired number of results per page

### Observed Behavior

- Page does not refresh after selecting the number of results per page.

<img width="405" alt="screen shot 2019-01-26 at 1 20 17 pm" src="https://user-images.githubusercontent.com/17339017/51791200-5738c180-216d-11e9-8703-ba7b8c2ef501.png">

- Works fine in Firefox.

**Comment by respawner** [comment]
I don't have this issue (tested on Chrome, Firefox and Safari). Did you try clearing the cache?

**Comment by jlixfeld** [comment]
Thanks!  That fixed it.
