### ISSUE TITLE
Import routers - clarify platform options

### ISSUE THREAD

**Issue by FredNeuberger** [respawner/peering-manager#9]
Hey,

I just tested the import function for the routers and ran into a smaller issue in regards to the platform.
Tried several things there for JunOS, but ended up in looking at the SQLite DB to find out that it is "junos". 

Did I miss anything?

I case I didn't, maybe a small hint in the "CSV Format" section on the import page is the best thing to do. Also searched the documentation, but couldn't find anything there.

Cheers

**Comment by jnikoletich** [comment]
@FredNeuberger  I think that since it is using the platform type to pass to NAPALM, that basic NAPALM naming conventions should be used. 

Before I did the import, I did add a router manually and saw the drop-down options as well. So that helped me.

**Comment by FredNeuberger** [comment]
@jnikoletich I tried the drop-down options as well, but that is different to what is being stored in the SQLite DB and therefore what is being used with the import function where you provide lots of routers in CSV format. I have even checked the admin -> Admin thingy, which seems to be some kind of frontend for the DB. The GUI just mentions 'Juniper JUNOS', Cisco IOS-XR' and 'Other'

Here an example from the DB:
```
select * from peering_router;
...
12|Juniper-Box|1.1.1.3||junos
13|IOS-XR|1.1.1.1||iosxr
14|OTHER|1.1.1.2||
```

peering/models.py does have the string "The router platform, used to interact with it" in line 258.
I tried to change that, but couldn't see any effect on my sandbox setup. Not sure how this pre-compiled caching stuff works.

@respawner Maybe you can include something like "(iosxr,junos or leave empty for other)" there.

And yes, @jnikoletich, you are right: models.py mentions "# Platform constants, based on NAPALM drivers"



Sorry if I'm being to meticulous.

**Comment by respawner** [comment]
I think that you found a bug here because we are supposed to use the standard name that you can see in the UI. The code is supposed to then put the proper value in the database (which is actually the NAPALM driver name).

I need to investigate and fix why it does not work when you use the platform name in the import feature.   Moreover maybe we should display a hint in the CSV format section of the page by listing the possible values.

**Comment by FredNeuberger** [comment]
I've created a PR with the hint.
Tried that yesterday already but it wasn't working because I screwed up with the ) at the end.
Today I was wondering why gunicorn was restarting all the time ...

Anyway, it is working now. Not sure if you want to present that in another way.

**Comment by respawner** [comment]
I'm currently testing a more generic patch that make it work like it should.

I'll commit and push it as soon as I consider it ready.
