### ISSUE TITLE
"Hide" available peering sessions

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#92]
### Environment
* Python version:  3.5.3
* Peering Manager version:  master

### Proposed Functionality

- Add an option for available peering sessions that hides the session from view.
- The hide option should be available to be bulk-edited to hide multiple sessions at once.
- Present a means to be able to view all hidden sessions with the same bulk-editable parameters for a normal session to allow a session to be unhidden and provisioned from the hidden view area.
- If a search is performed that matches a session that is hidden, show the hidden session in the results list with an indicator that the session is hidden.

### Use Case

- We would like to hide autonomous systems that do not maintain their PeeringDB entries so we don't try to contact them accidentally to set up peering sessions with them.

### External Dependencies

**Comment by respawner** [comment]
The available peers list shows only details coming from PeeringDB. Just to make sure that I understand the FR correctly, you'd like to be able to hide available peers that do not maintain their PeeringDB records properly even if the list is generated from these records?

**Comment by jlixfeld** [comment]
Not maintaining PeeringDB records is one example, yes. But the reason someone might want to hide an available peer could be for something else too.  Maybe they are bad actor or something.

**Comment by ggiesen** [comment]
The other option

> 
> 
> Not maintaining PeeringDB records is one example, yes. But the reason someone might want to hide an available peer could be for something else too. Maybe they are bad actor or something.

Another example is peers for whom you don't meet their peering requirements.
